//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace TehHotel.Gui.Test.RentACarVozilaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IVozila", Namespace="http://tempuri.org/")]
    public partial class Vozila : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dodajVoziloOperationCompleted;
        
        private System.Threading.SendOrPostCallback spremeniVoziloOperationCompleted;
        
        private System.Threading.SendOrPostCallback odstraniVoziloOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledVsehVozilOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledRazpolozljivihVozilOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledVozilPoPoslovalniciOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Vozila() {
            this.Url = global::TehHotel.Gui.Test.Properties.Settings.Default.TehHotel_Gui_Test_RentACarVozilaService_Vozila;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dodajVoziloCompletedEventHandler dodajVoziloCompleted;
        
        /// <remarks/>
        public event spremeniVoziloCompletedEventHandler spremeniVoziloCompleted;
        
        /// <remarks/>
        public event odstraniVoziloCompletedEventHandler odstraniVoziloCompleted;
        
        /// <remarks/>
        public event pregledVsehVozilCompletedEventHandler pregledVsehVozilCompleted;
        
        /// <remarks/>
        public event pregledRazpolozljivihVozilCompletedEventHandler pregledRazpolozljivihVozilCompleted;
        
        /// <remarks/>
        public event pregledVozilPoPoslovalniciCompletedEventHandler pregledVozilPoPoslovalniciCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVozila/dodajVozilo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dodajVozilo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Vozilo vozilo) {
            object[] results = this.Invoke("dodajVozilo", new object[] {
                        vozilo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dodajVoziloAsync(Vozilo vozilo) {
            this.dodajVoziloAsync(vozilo, null);
        }
        
        /// <remarks/>
        public void dodajVoziloAsync(Vozilo vozilo, object userState) {
            if ((this.dodajVoziloOperationCompleted == null)) {
                this.dodajVoziloOperationCompleted = new System.Threading.SendOrPostCallback(this.OndodajVoziloOperationCompleted);
            }
            this.InvokeAsync("dodajVozilo", new object[] {
                        vozilo}, this.dodajVoziloOperationCompleted, userState);
        }
        
        private void OndodajVoziloOperationCompleted(object arg) {
            if ((this.dodajVoziloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dodajVoziloCompleted(this, new dodajVoziloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVozila/spremeniVozilo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spremeniVozilo(int idVozilo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idVoziloSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Vozilo vozilo) {
            object[] results = this.Invoke("spremeniVozilo", new object[] {
                        idVozilo,
                        idVoziloSpecified,
                        vozilo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void spremeniVoziloAsync(int idVozilo, bool idVoziloSpecified, Vozilo vozilo) {
            this.spremeniVoziloAsync(idVozilo, idVoziloSpecified, vozilo, null);
        }
        
        /// <remarks/>
        public void spremeniVoziloAsync(int idVozilo, bool idVoziloSpecified, Vozilo vozilo, object userState) {
            if ((this.spremeniVoziloOperationCompleted == null)) {
                this.spremeniVoziloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnspremeniVoziloOperationCompleted);
            }
            this.InvokeAsync("spremeniVozilo", new object[] {
                        idVozilo,
                        idVoziloSpecified,
                        vozilo}, this.spremeniVoziloOperationCompleted, userState);
        }
        
        private void OnspremeniVoziloOperationCompleted(object arg) {
            if ((this.spremeniVoziloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.spremeniVoziloCompleted(this, new spremeniVoziloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVozila/odstraniVozilo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string odstraniVozilo(int idVozilo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idVoziloSpecified) {
            object[] results = this.Invoke("odstraniVozilo", new object[] {
                        idVozilo,
                        idVoziloSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void odstraniVoziloAsync(int idVozilo, bool idVoziloSpecified) {
            this.odstraniVoziloAsync(idVozilo, idVoziloSpecified, null);
        }
        
        /// <remarks/>
        public void odstraniVoziloAsync(int idVozilo, bool idVoziloSpecified, object userState) {
            if ((this.odstraniVoziloOperationCompleted == null)) {
                this.odstraniVoziloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnodstraniVoziloOperationCompleted);
            }
            this.InvokeAsync("odstraniVozilo", new object[] {
                        idVozilo,
                        idVoziloSpecified}, this.odstraniVoziloOperationCompleted, userState);
        }
        
        private void OnodstraniVoziloOperationCompleted(object arg) {
            if ((this.odstraniVoziloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.odstraniVoziloCompleted(this, new odstraniVoziloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVozila/pregledVsehVozil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RentACar2_Vozila")]
        public Vozilo[] pregledVsehVozil() {
            object[] results = this.Invoke("pregledVsehVozil", new object[0]);
            return ((Vozilo[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledVsehVozilAsync() {
            this.pregledVsehVozilAsync(null);
        }
        
        /// <remarks/>
        public void pregledVsehVozilAsync(object userState) {
            if ((this.pregledVsehVozilOperationCompleted == null)) {
                this.pregledVsehVozilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledVsehVozilOperationCompleted);
            }
            this.InvokeAsync("pregledVsehVozil", new object[0], this.pregledVsehVozilOperationCompleted, userState);
        }
        
        private void OnpregledVsehVozilOperationCompleted(object arg) {
            if ((this.pregledVsehVozilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledVsehVozilCompleted(this, new pregledVsehVozilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVozila/pregledRazpolozljivihVozil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RentACar2_Vozila")]
        public Vozilo[] pregledRazpolozljivihVozil() {
            object[] results = this.Invoke("pregledRazpolozljivihVozil", new object[0]);
            return ((Vozilo[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledRazpolozljivihVozilAsync() {
            this.pregledRazpolozljivihVozilAsync(null);
        }
        
        /// <remarks/>
        public void pregledRazpolozljivihVozilAsync(object userState) {
            if ((this.pregledRazpolozljivihVozilOperationCompleted == null)) {
                this.pregledRazpolozljivihVozilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledRazpolozljivihVozilOperationCompleted);
            }
            this.InvokeAsync("pregledRazpolozljivihVozil", new object[0], this.pregledRazpolozljivihVozilOperationCompleted, userState);
        }
        
        private void OnpregledRazpolozljivihVozilOperationCompleted(object arg) {
            if ((this.pregledRazpolozljivihVozilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledRazpolozljivihVozilCompleted(this, new pregledRazpolozljivihVozilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVozila/pregledVozilPoPoslovalnici", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RentACar2_Vozila")]
        public Vozilo[] pregledVozilPoPoslovalnici(int idPoslovalnica, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idPoslovalnicaSpecified) {
            object[] results = this.Invoke("pregledVozilPoPoslovalnici", new object[] {
                        idPoslovalnica,
                        idPoslovalnicaSpecified});
            return ((Vozilo[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledVozilPoPoslovalniciAsync(int idPoslovalnica, bool idPoslovalnicaSpecified) {
            this.pregledVozilPoPoslovalniciAsync(idPoslovalnica, idPoslovalnicaSpecified, null);
        }
        
        /// <remarks/>
        public void pregledVozilPoPoslovalniciAsync(int idPoslovalnica, bool idPoslovalnicaSpecified, object userState) {
            if ((this.pregledVozilPoPoslovalniciOperationCompleted == null)) {
                this.pregledVozilPoPoslovalniciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledVozilPoPoslovalniciOperationCompleted);
            }
            this.InvokeAsync("pregledVozilPoPoslovalnici", new object[] {
                        idPoslovalnica,
                        idPoslovalnicaSpecified}, this.pregledVozilPoPoslovalniciOperationCompleted, userState);
        }
        
        private void OnpregledVozilPoPoslovalniciOperationCompleted(object arg) {
            if ((this.pregledVozilPoPoslovalniciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledVozilPoPoslovalniciCompleted(this, new pregledVozilPoPoslovalniciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RentACar2_Vozila")]
    public partial class Vozilo {
        
        private double cenaDanField;
        
        private bool cenaDanFieldSpecified;
        
        private string gorivoField;
        
        private int idPoslovalnicaField;
        
        private bool idPoslovalnicaFieldSpecified;
        
        private int idVoziloField;
        
        private bool idVoziloFieldSpecified;
        
        private string klimaField;
        
        private int letnikField;
        
        private bool letnikFieldSpecified;
        
        private string menjalnikField;
        
        private string mocMotorjaField;
        
        private string nazivField;
        
        private string razpolozljivostField;
        
        private int steviloOsebField;
        
        private bool steviloOsebFieldSpecified;
        
        private int steviloVratField;
        
        private bool steviloVratFieldSpecified;
        
        private string tipField;
        
        private string vinjetaField;
        
        /// <remarks/>
        public double CenaDan {
            get {
                return this.cenaDanField;
            }
            set {
                this.cenaDanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CenaDanSpecified {
            get {
                return this.cenaDanFieldSpecified;
            }
            set {
                this.cenaDanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gorivo {
            get {
                return this.gorivoField;
            }
            set {
                this.gorivoField = value;
            }
        }
        
        /// <remarks/>
        public int IdPoslovalnica {
            get {
                return this.idPoslovalnicaField;
            }
            set {
                this.idPoslovalnicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdPoslovalnicaSpecified {
            get {
                return this.idPoslovalnicaFieldSpecified;
            }
            set {
                this.idPoslovalnicaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdVozilo {
            get {
                return this.idVoziloField;
            }
            set {
                this.idVoziloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdVoziloSpecified {
            get {
                return this.idVoziloFieldSpecified;
            }
            set {
                this.idVoziloFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Klima {
            get {
                return this.klimaField;
            }
            set {
                this.klimaField = value;
            }
        }
        
        /// <remarks/>
        public int Letnik {
            get {
                return this.letnikField;
            }
            set {
                this.letnikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LetnikSpecified {
            get {
                return this.letnikFieldSpecified;
            }
            set {
                this.letnikFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Menjalnik {
            get {
                return this.menjalnikField;
            }
            set {
                this.menjalnikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MocMotorja {
            get {
                return this.mocMotorjaField;
            }
            set {
                this.mocMotorjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Razpolozljivost {
            get {
                return this.razpolozljivostField;
            }
            set {
                this.razpolozljivostField = value;
            }
        }
        
        /// <remarks/>
        public int SteviloOseb {
            get {
                return this.steviloOsebField;
            }
            set {
                this.steviloOsebField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SteviloOsebSpecified {
            get {
                return this.steviloOsebFieldSpecified;
            }
            set {
                this.steviloOsebFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int SteviloVrat {
            get {
                return this.steviloVratField;
            }
            set {
                this.steviloVratField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SteviloVratSpecified {
            get {
                return this.steviloVratFieldSpecified;
            }
            set {
                this.steviloVratFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tip {
            get {
                return this.tipField;
            }
            set {
                this.tipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Vinjeta {
            get {
                return this.vinjetaField;
            }
            set {
                this.vinjetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void dodajVoziloCompletedEventHandler(object sender, dodajVoziloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dodajVoziloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dodajVoziloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void spremeniVoziloCompletedEventHandler(object sender, spremeniVoziloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class spremeniVoziloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal spremeniVoziloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void odstraniVoziloCompletedEventHandler(object sender, odstraniVoziloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class odstraniVoziloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal odstraniVoziloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledVsehVozilCompletedEventHandler(object sender, pregledVsehVozilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledVsehVozilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledVsehVozilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vozilo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vozilo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledRazpolozljivihVozilCompletedEventHandler(object sender, pregledRazpolozljivihVozilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledRazpolozljivihVozilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledRazpolozljivihVozilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vozilo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vozilo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledVozilPoPoslovalniciCompletedEventHandler(object sender, pregledVozilPoPoslovalniciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledVozilPoPoslovalniciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledVozilPoPoslovalniciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vozilo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vozilo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591