//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TehHotel.Gui.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1476/HotelService.svc")]
        public string TehHotel_Gui_Test_HotelService_HotelService {
            get {
                return ((string)(this["TehHotel_Gui_Test_HotelService_HotelService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1476/RezervacijaService.svc")]
        public string TehHotel_Gui_Test_RezervacijaService_RezervacijaService {
            get {
                return ((string)(this["TehHotel_Gui_Test_RezervacijaService_RezervacijaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1476/StrankaService.svc")]
        public string TehHotel_Gui_Test_StrankaService_StrankaService {
            get {
                return ((string)(this["TehHotel_Gui_Test_StrankaService_StrankaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://164.8.251.93:8080/KBP-Banka/KBP-Stranke")]
        public string TehHotel_Gui_Test_BankaService_KBP_Stranke {
            get {
                return ((string)(this["TehHotel_Gui_Test_BankaService_KBP_Stranke"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://164.8.251.93:8080/KBP_Prijava/KBP_Prijava")]
        public string TehHotel_Gui_Test_BankaSecureService_KBP_Prijava {
            get {
                return ((string)(this["TehHotel_Gui_Test_BankaSecureService_KBP_Prijava"]));
            }
        }
        [global::System.Configuration.DefaultSettingValueAttribute("http://164.8.251.93/SOATravel/letalec2/ForeachAirlines.svc")]
        public string TehHotel_Gui_Test_LetalisceService_Letalec2 {
            get {
                return ((string)(this["TehHotel_Gui_Test_LetalisceService_Letalec2"]));
            }
        }
    }
}
