//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace TehHotel.Gui.Test.StrankaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_StrankaService", Namespace="http://tempuri.org/")]
    public partial class StrankaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateStrankaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadStrankaOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStrankaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteStrankaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListStrankaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StrankaService() {
            this.Url = global::TehHotel.Gui.Test.Properties.Settings.Default.TehHotel_Gui_Test_StrankaService_StrankaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateStrankaCompletedEventHandler CreateStrankaCompleted;
        
        /// <remarks/>
        public event ReadStrankaCompletedEventHandler ReadStrankaCompleted;
        
        /// <remarks/>
        public event UpdateStrankaCompletedEventHandler UpdateStrankaCompleted;
        
        /// <remarks/>
        public event DeleteStrankaCompletedEventHandler DeleteStrankaCompleted;
        
        /// <remarks/>
        public event ListStrankaCompletedEventHandler ListStrankaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//www.tehhotel.com/StrankaService/CreateStranka", RequestNamespace="http//www.tehhotel.com/", ResponseNamespace="http//www.tehhotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateStranka([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Stranka s, out bool CreateStrankaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CreateStrankaResultSpecified) {
            object[] results = this.Invoke("CreateStranka", new object[] {
                        s});
            CreateStrankaResult = ((bool)(results[0]));
            CreateStrankaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CreateStrankaAsync(Stranka s) {
            this.CreateStrankaAsync(s, null);
        }
        
        /// <remarks/>
        public void CreateStrankaAsync(Stranka s, object userState) {
            if ((this.CreateStrankaOperationCompleted == null)) {
                this.CreateStrankaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateStrankaOperationCompleted);
            }
            this.InvokeAsync("CreateStranka", new object[] {
                        s}, this.CreateStrankaOperationCompleted, userState);
        }
        
        private void OnCreateStrankaOperationCompleted(object arg) {
            if ((this.CreateStrankaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateStrankaCompleted(this, new CreateStrankaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//www.tehhotel.com/StrankaService/ReadStranka", RequestNamespace="http//www.tehhotel.com/", ResponseNamespace="http//www.tehhotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Stranka ReadStranka(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("ReadStranka", new object[] {
                        id,
                        idSpecified});
            return ((Stranka)(results[0]));
        }
        
        /// <remarks/>
        public void ReadStrankaAsync(int id, bool idSpecified) {
            this.ReadStrankaAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void ReadStrankaAsync(int id, bool idSpecified, object userState) {
            if ((this.ReadStrankaOperationCompleted == null)) {
                this.ReadStrankaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadStrankaOperationCompleted);
            }
            this.InvokeAsync("ReadStranka", new object[] {
                        id,
                        idSpecified}, this.ReadStrankaOperationCompleted, userState);
        }
        
        private void OnReadStrankaOperationCompleted(object arg) {
            if ((this.ReadStrankaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadStrankaCompleted(this, new ReadStrankaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//www.tehhotel.com/StrankaService/UpdateStranka", RequestNamespace="http//www.tehhotel.com/", ResponseNamespace="http//www.tehhotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateStranka([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Stranka s, out bool UpdateStrankaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateStrankaResultSpecified) {
            object[] results = this.Invoke("UpdateStranka", new object[] {
                        s});
            UpdateStrankaResult = ((bool)(results[0]));
            UpdateStrankaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void UpdateStrankaAsync(Stranka s) {
            this.UpdateStrankaAsync(s, null);
        }
        
        /// <remarks/>
        public void UpdateStrankaAsync(Stranka s, object userState) {
            if ((this.UpdateStrankaOperationCompleted == null)) {
                this.UpdateStrankaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStrankaOperationCompleted);
            }
            this.InvokeAsync("UpdateStranka", new object[] {
                        s}, this.UpdateStrankaOperationCompleted, userState);
        }
        
        private void OnUpdateStrankaOperationCompleted(object arg) {
            if ((this.UpdateStrankaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStrankaCompleted(this, new UpdateStrankaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//www.tehhotel.com/StrankaService/DeleteStranka", RequestNamespace="http//www.tehhotel.com/", ResponseNamespace="http//www.tehhotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteStranka(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, out bool DeleteStrankaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool DeleteStrankaResultSpecified) {
            object[] results = this.Invoke("DeleteStranka", new object[] {
                        id,
                        idSpecified});
            DeleteStrankaResult = ((bool)(results[0]));
            DeleteStrankaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void DeleteStrankaAsync(int id, bool idSpecified) {
            this.DeleteStrankaAsync(id, idSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteStrankaAsync(int id, bool idSpecified, object userState) {
            if ((this.DeleteStrankaOperationCompleted == null)) {
                this.DeleteStrankaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteStrankaOperationCompleted);
            }
            this.InvokeAsync("DeleteStranka", new object[] {
                        id,
                        idSpecified}, this.DeleteStrankaOperationCompleted, userState);
        }
        
        private void OnDeleteStrankaOperationCompleted(object arg) {
            if ((this.DeleteStrankaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteStrankaCompleted(this, new DeleteStrankaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http//www.tehhotel.com/StrankaService/ListStranka", RequestNamespace="http//www.tehhotel.com/", ResponseNamespace="http//www.tehhotel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Stranka[] ListStranka() {
            object[] results = this.Invoke("ListStranka", new object[0]);
            return ((Stranka[])(results[0]));
        }
        
        /// <remarks/>
        public void ListStrankaAsync() {
            this.ListStrankaAsync(null);
        }
        
        /// <remarks/>
        public void ListStrankaAsync(object userState) {
            if ((this.ListStrankaOperationCompleted == null)) {
                this.ListStrankaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListStrankaOperationCompleted);
            }
            this.InvokeAsync("ListStranka", new object[0], this.ListStrankaOperationCompleted, userState);
        }
        
        private void OnListStrankaOperationCompleted(object arg) {
            if ((this.ListStrankaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListStrankaCompleted(this, new ListStrankaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http//www.tehhotel.com/")]
    public partial class Stranka {
        
        private System.DateTime datumRojstvaField;
        
        private bool datumRojstvaFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private Identifikacija identifikacijaField;
        
        private string imeField;
        
        private Naslov naslovField;
        
        private string priimekField;
        
        private string id1Field;
        
        private string refField;
        
        /// <remarks/>
        public System.DateTime DatumRojstva {
            get {
                return this.datumRojstvaField;
            }
            set {
                this.datumRojstvaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumRojstvaSpecified {
            get {
                return this.datumRojstvaFieldSpecified;
            }
            set {
                this.datumRojstvaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Identifikacija Identifikacija {
            get {
                return this.identifikacijaField;
            }
            set {
                this.identifikacijaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Naslov Naslov {
            get {
                return this.naslovField;
            }
            set {
                this.naslovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Priimek {
            get {
                return this.priimekField;
            }
            set {
                this.priimekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Id", Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="ID")]
        public string Id1 {
            get {
                return this.id1Field;
            }
            set {
                this.id1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="IDREF")]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http//www.tehhotel.com/")]
    public partial class Identifikacija {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string tipField;
        
        private string vrednostField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tip {
            get {
                return this.tipField;
            }
            set {
                this.tipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Vrednost {
            get {
                return this.vrednostField;
            }
            set {
                this.vrednostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http//www.tehhotel.com/")]
    public partial class Naslov {
        
        private string drzavaField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string krajField;
        
        private int postnaStevilkaField;
        
        private bool postnaStevilkaFieldSpecified;
        
        private string ulicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Drzava {
            get {
                return this.drzavaField;
            }
            set {
                this.drzavaField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Kraj {
            get {
                return this.krajField;
            }
            set {
                this.krajField = value;
            }
        }
        
        /// <remarks/>
        public int PostnaStevilka {
            get {
                return this.postnaStevilkaField;
            }
            set {
                this.postnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostnaStevilkaSpecified {
            get {
                return this.postnaStevilkaFieldSpecified;
            }
            set {
                this.postnaStevilkaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateStrankaCompletedEventHandler(object sender, CreateStrankaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateStrankaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateStrankaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool CreateStrankaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CreateStrankaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadStrankaCompletedEventHandler(object sender, ReadStrankaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadStrankaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadStrankaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stranka Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stranka)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateStrankaCompletedEventHandler(object sender, UpdateStrankaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStrankaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStrankaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool UpdateStrankaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool UpdateStrankaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteStrankaCompletedEventHandler(object sender, DeleteStrankaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteStrankaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteStrankaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool DeleteStrankaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool DeleteStrankaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ListStrankaCompletedEventHandler(object sender, ListStrankaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListStrankaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListStrankaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stranka[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stranka[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591