//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace TehHotel.Gui.Test.BankaService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Net;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KBPBusinessWSImplPortBinding", Namespace="http://ws.kbp.soa.feri.uni_mb.si/")]
    public partial class KBPStranke : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback izdajRacunOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledNeplacanihIzdanihRacunovOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledPlacanihIzdanihRacunovOperationCompleted;
        
        private System.Threading.SendOrPostCallback preklicAvtomatskegaPlacevanjaRacunaOperationCompleted;
        
        private System.Threading.SendOrPostCallback preklicNeplacanegaRacunaOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledPrometaOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledStanjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledNeplacanihRacunovOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledPlacanihRacunovOperationCompleted;
        
        private System.Threading.SendOrPostCallback placiloSKarticoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledPlacilSKarticoOperationCompleted;
        
        private System.Threading.SendOrPostCallback prenosDenarjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback avtomatskoPlacevanjeRacunaOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledKreditovNaRacunuOperationCompleted;
        
        private System.Threading.SendOrPostCallback prijavaOperationCompleted;
        
        private System.Threading.SendOrPostCallback placajRacunOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;

        private string upime = "tehhotel";
        private string geslo = "123456";

        public void SetUpime(string upime) { this.upime = upime; }
        public void SetGeslo(string geslo) { this.geslo = geslo; }

        protected override WebRequest GetWebRequest(Uri uri)
        {
            HttpWebRequest request = (HttpWebRequest)base.GetWebRequest(uri);
            request.Headers.Add("uporabniskoIme", upime);
            request.Headers.Add("geslo", geslo);
            return request;
        }

        /// <remarks/>
        public KBPStranke() {
            this.Url = global::TehHotel.Gui.Test.Properties.Settings.Default.TehHotel_Gui_Test_BankaService_KBP_Stranke;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event izdajRacunCompletedEventHandler izdajRacunCompleted;
        
        /// <remarks/>
        public event pregledNeplacanihIzdanihRacunovCompletedEventHandler pregledNeplacanihIzdanihRacunovCompleted;
        
        /// <remarks/>
        public event pregledPlacanihIzdanihRacunovCompletedEventHandler pregledPlacanihIzdanihRacunovCompleted;
        
        /// <remarks/>
        public event preklicAvtomatskegaPlacevanjaRacunaCompletedEventHandler preklicAvtomatskegaPlacevanjaRacunaCompleted;
        
        /// <remarks/>
        public event preklicNeplacanegaRacunaCompletedEventHandler preklicNeplacanegaRacunaCompleted;
        
        /// <remarks/>
        public event pregledPrometaCompletedEventHandler pregledPrometaCompleted;
        
        /// <remarks/>
        public event pregledStanjaCompletedEventHandler pregledStanjaCompleted;
        
        /// <remarks/>
        public event pregledNeplacanihRacunovCompletedEventHandler pregledNeplacanihRacunovCompleted;
        
        /// <remarks/>
        public event pregledPlacanihRacunovCompletedEventHandler pregledPlacanihRacunovCompleted;
        
        /// <remarks/>
        public event placiloSKarticoCompletedEventHandler placiloSKarticoCompleted;
        
        /// <remarks/>
        public event pregledPlacilSKarticoCompletedEventHandler pregledPlacilSKarticoCompleted;
        
        /// <remarks/>
        public event prenosDenarjaCompletedEventHandler prenosDenarjaCompleted;
        
        /// <remarks/>
        public event avtomatskoPlacevanjeRacunaCompletedEventHandler avtomatskoPlacevanjeRacunaCompleted;
        
        /// <remarks/>
        public event pregledKreditovNaRacunuCompletedEventHandler pregledKreditovNaRacunuCompleted;
        
        /// <remarks/>
        public event prijavaCompletedEventHandler prijavaCompleted;
        
        /// <remarks/>
        public event placajRacunCompletedEventHandler placajRacunCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Odgovor", Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
        public Odgovor izdajRacun([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")] IzdaniRacun IzdaniRacun) {
            object[] results = this.Invoke("izdajRacun", new object[] {
                        IzdaniRacun});
            return ((Odgovor)(results[0]));
        }
        
        /// <remarks/>
        public void izdajRacunAsync(IzdaniRacun IzdaniRacun) {
            this.izdajRacunAsync(IzdaniRacun, null);
        }
        
        /// <remarks/>
        public void izdajRacunAsync(IzdaniRacun IzdaniRacun, object userState) {
            if ((this.izdajRacunOperationCompleted == null)) {
                this.izdajRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnizdajRacunOperationCompleted);
            }
            this.InvokeAsync("izdajRacun", new object[] {
                        IzdaniRacun}, this.izdajRacunOperationCompleted, userState);
        }
        
        private void OnizdajRacunOperationCompleted(object arg) {
            if ((this.izdajRacunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.izdajRacunCompleted(this, new izdajRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IzdaniRacun", Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
        public IzdaniRacun[] pregledNeplacanihIzdanihRacunov([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaTRR) {
            object[] results = this.Invoke("pregledNeplacanihIzdanihRacunov", new object[] {
                        stevilkaTRR});
            return ((IzdaniRacun[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledNeplacanihIzdanihRacunovAsync(string stevilkaTRR) {
            this.pregledNeplacanihIzdanihRacunovAsync(stevilkaTRR, null);
        }
        
        /// <remarks/>
        public void pregledNeplacanihIzdanihRacunovAsync(string stevilkaTRR, object userState) {
            if ((this.pregledNeplacanihIzdanihRacunovOperationCompleted == null)) {
                this.pregledNeplacanihIzdanihRacunovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledNeplacanihIzdanihRacunovOperationCompleted);
            }
            this.InvokeAsync("pregledNeplacanihIzdanihRacunov", new object[] {
                        stevilkaTRR}, this.pregledNeplacanihIzdanihRacunovOperationCompleted, userState);
        }
        
        private void OnpregledNeplacanihIzdanihRacunovOperationCompleted(object arg) {
            if ((this.pregledNeplacanihIzdanihRacunovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledNeplacanihIzdanihRacunovCompleted(this, new pregledNeplacanihIzdanihRacunovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IzdaniRacun", Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
        public IzdaniRacun[] pregledPlacanihIzdanihRacunov([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaTRR) {
            object[] results = this.Invoke("pregledPlacanihIzdanihRacunov", new object[] {
                        stevilkaTRR});
            return ((IzdaniRacun[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledPlacanihIzdanihRacunovAsync(string stevilkaTRR) {
            this.pregledPlacanihIzdanihRacunovAsync(stevilkaTRR, null);
        }
        
        /// <remarks/>
        public void pregledPlacanihIzdanihRacunovAsync(string stevilkaTRR, object userState) {
            if ((this.pregledPlacanihIzdanihRacunovOperationCompleted == null)) {
                this.pregledPlacanihIzdanihRacunovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledPlacanihIzdanihRacunovOperationCompleted);
            }
            this.InvokeAsync("pregledPlacanihIzdanihRacunov", new object[] {
                        stevilkaTRR}, this.pregledPlacanihIzdanihRacunovOperationCompleted, userState);
        }
        
        private void OnpregledPlacanihIzdanihRacunovOperationCompleted(object arg) {
            if ((this.pregledPlacanihIzdanihRacunovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledPlacanihIzdanihRacunovCompleted(this, new pregledPlacanihIzdanihRacunovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Odgovor", Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
        public Odgovor preklicAvtomatskegaPlacevanjaRacuna([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")] IzdaniRacun IzdaniRacun) {
            object[] results = this.Invoke("preklicAvtomatskegaPlacevanjaRacuna", new object[] {
                        IzdaniRacun});
            return ((Odgovor)(results[0]));
        }
        
        /// <remarks/>
        public void preklicAvtomatskegaPlacevanjaRacunaAsync(IzdaniRacun IzdaniRacun) {
            this.preklicAvtomatskegaPlacevanjaRacunaAsync(IzdaniRacun, null);
        }
        
        /// <remarks/>
        public void preklicAvtomatskegaPlacevanjaRacunaAsync(IzdaniRacun IzdaniRacun, object userState) {
            if ((this.preklicAvtomatskegaPlacevanjaRacunaOperationCompleted == null)) {
                this.preklicAvtomatskegaPlacevanjaRacunaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpreklicAvtomatskegaPlacevanjaRacunaOperationCompleted);
            }
            this.InvokeAsync("preklicAvtomatskegaPlacevanjaRacuna", new object[] {
                        IzdaniRacun}, this.preklicAvtomatskegaPlacevanjaRacunaOperationCompleted, userState);
        }
        
        private void OnpreklicAvtomatskegaPlacevanjaRacunaOperationCompleted(object arg) {
            if ((this.preklicAvtomatskegaPlacevanjaRacunaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.preklicAvtomatskegaPlacevanjaRacunaCompleted(this, new preklicAvtomatskegaPlacevanjaRacunaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Odgovor", Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
        public Odgovor preklicNeplacanegaRacuna([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")] IzdaniRacun IzdaniRacun) {
            object[] results = this.Invoke("preklicNeplacanegaRacuna", new object[] {
                        IzdaniRacun});
            return ((Odgovor)(results[0]));
        }
        
        /// <remarks/>
        public void preklicNeplacanegaRacunaAsync(IzdaniRacun IzdaniRacun) {
            this.preklicNeplacanegaRacunaAsync(IzdaniRacun, null);
        }
        
        /// <remarks/>
        public void preklicNeplacanegaRacunaAsync(IzdaniRacun IzdaniRacun, object userState) {
            if ((this.preklicNeplacanegaRacunaOperationCompleted == null)) {
                this.preklicNeplacanegaRacunaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpreklicNeplacanegaRacunaOperationCompleted);
            }
            this.InvokeAsync("preklicNeplacanegaRacuna", new object[] {
                        IzdaniRacun}, this.preklicNeplacanegaRacunaOperationCompleted, userState);
        }
        
        private void OnpreklicNeplacanegaRacunaOperationCompleted(object arg) {
            if ((this.preklicNeplacanegaRacunaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.preklicNeplacanegaRacunaCompleted(this, new preklicNeplacanegaRacunaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PregledPrometa", Namespace="http://www.feri.uni-mb.si/soa/KBP/pregledPrometa")]
        public PregledPrometa[] pregledPrometa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaTRR) {
            object[] results = this.Invoke("pregledPrometa", new object[] {
                        stevilkaTRR});
            return ((PregledPrometa[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledPrometaAsync(string stevilkaTRR) {
            this.pregledPrometaAsync(stevilkaTRR, null);
        }
        
        /// <remarks/>
        public void pregledPrometaAsync(string stevilkaTRR, object userState) {
            if ((this.pregledPrometaOperationCompleted == null)) {
                this.pregledPrometaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledPrometaOperationCompleted);
            }
            this.InvokeAsync("pregledPrometa", new object[] {
                        stevilkaTRR}, this.pregledPrometaOperationCompleted, userState);
        }
        
        private void OnpregledPrometaOperationCompleted(object arg) {
            if ((this.pregledPrometaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledPrometaCompleted(this, new pregledPrometaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pregledStanja([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaTRR) {
            object[] results = this.Invoke("pregledStanja", new object[] {
                        stevilkaTRR});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void pregledStanjaAsync(string stevilkaTRR) {
            this.pregledStanjaAsync(stevilkaTRR, null);
        }
        
        /// <remarks/>
        public void pregledStanjaAsync(string stevilkaTRR, object userState) {
            if ((this.pregledStanjaOperationCompleted == null)) {
                this.pregledStanjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledStanjaOperationCompleted);
            }
            this.InvokeAsync("pregledStanja", new object[] {
                        stevilkaTRR}, this.pregledStanjaOperationCompleted, userState);
        }
        
        private void OnpregledStanjaOperationCompleted(object arg) {
            if ((this.pregledStanjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledStanjaCompleted(this, new pregledStanjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IzdaniRacun", Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
        public IzdaniRacun[] pregledNeplacanihRacunov([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaTRR) {
            object[] results = this.Invoke("pregledNeplacanihRacunov", new object[] {
                        stevilkaTRR});
            return ((IzdaniRacun[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledNeplacanihRacunovAsync(string stevilkaTRR) {
            this.pregledNeplacanihRacunovAsync(stevilkaTRR, null);
        }
        
        /// <remarks/>
        public void pregledNeplacanihRacunovAsync(string stevilkaTRR, object userState) {
            if ((this.pregledNeplacanihRacunovOperationCompleted == null)) {
                this.pregledNeplacanihRacunovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledNeplacanihRacunovOperationCompleted);
            }
            this.InvokeAsync("pregledNeplacanihRacunov", new object[] {
                        stevilkaTRR}, this.pregledNeplacanihRacunovOperationCompleted, userState);
        }
        
        private void OnpregledNeplacanihRacunovOperationCompleted(object arg) {
            if ((this.pregledNeplacanihRacunovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledNeplacanihRacunovCompleted(this, new pregledNeplacanihRacunovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IzdaniRacun", Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
        public IzdaniRacun[] pregledPlacanihRacunov([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaTRR) {
            object[] results = this.Invoke("pregledPlacanihRacunov", new object[] {
                        stevilkaTRR});
            return ((IzdaniRacun[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledPlacanihRacunovAsync(string stevilkaTRR) {
            this.pregledPlacanihRacunovAsync(stevilkaTRR, null);
        }
        
        /// <remarks/>
        public void pregledPlacanihRacunovAsync(string stevilkaTRR, object userState) {
            if ((this.pregledPlacanihRacunovOperationCompleted == null)) {
                this.pregledPlacanihRacunovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledPlacanihRacunovOperationCompleted);
            }
            this.InvokeAsync("pregledPlacanihRacunov", new object[] {
                        stevilkaTRR}, this.pregledPlacanihRacunovOperationCompleted, userState);
        }
        
        private void OnpregledPlacanihRacunovOperationCompleted(object arg) {
            if ((this.pregledPlacanihRacunovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledPlacanihRacunovCompleted(this, new pregledPlacanihRacunovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Odgovor", Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
        public Odgovor placiloSKartico([System.Xml.Serialization.XmlElementAttribute("PlaciloSKartico", Namespace="http://www.feri.uni-mb.si/soa/KBP/placiloSKartico")] PlaciloSKartico PlaciloSKartico1) {
            object[] results = this.Invoke("placiloSKartico", new object[] {
                        PlaciloSKartico1});
            return ((Odgovor)(results[0]));
        }
        
        /// <remarks/>
        public void placiloSKarticoAsync(PlaciloSKartico PlaciloSKartico1) {
            this.placiloSKarticoAsync(PlaciloSKartico1, null);
        }
        
        /// <remarks/>
        public void placiloSKarticoAsync(PlaciloSKartico PlaciloSKartico1, object userState) {
            if ((this.placiloSKarticoOperationCompleted == null)) {
                this.placiloSKarticoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnplaciloSKarticoOperationCompleted);
            }
            this.InvokeAsync("placiloSKartico", new object[] {
                        PlaciloSKartico1}, this.placiloSKarticoOperationCompleted, userState);
        }
        
        private void OnplaciloSKarticoOperationCompleted(object arg) {
            if ((this.placiloSKarticoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.placiloSKarticoCompleted(this, new placiloSKarticoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("PlaciloSKartico", Namespace="http://www.feri.uni-mb.si/soa/KBP/placiloSKartico")]
        public PlaciloSKartico[] pregledPlacilSKartico([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaKartice) {
            object[] results = this.Invoke("pregledPlacilSKartico", new object[] {
                        stevilkaKartice});
            return ((PlaciloSKartico[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledPlacilSKarticoAsync(string stevilkaKartice) {
            this.pregledPlacilSKarticoAsync(stevilkaKartice, null);
        }
        
        /// <remarks/>
        public void pregledPlacilSKarticoAsync(string stevilkaKartice, object userState) {
            if ((this.pregledPlacilSKarticoOperationCompleted == null)) {
                this.pregledPlacilSKarticoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledPlacilSKarticoOperationCompleted);
            }
            this.InvokeAsync("pregledPlacilSKartico", new object[] {
                        stevilkaKartice}, this.pregledPlacilSKarticoOperationCompleted, userState);
        }
        
        private void OnpregledPlacilSKarticoOperationCompleted(object arg) {
            if ((this.pregledPlacilSKarticoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledPlacilSKarticoCompleted(this, new pregledPlacilSKarticoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Odgovor", Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
        public Odgovor prenosDenarja([System.Xml.Serialization.XmlElementAttribute("PrenosDenarja", Namespace="http://www.feri.uni-mb.si/soa/KBP/prenosDenarja")] PrenosDenarja PrenosDenarja1) {
            object[] results = this.Invoke("prenosDenarja", new object[] {
                        PrenosDenarja1});
            return ((Odgovor)(results[0]));
        }
        
        /// <remarks/>
        public void prenosDenarjaAsync(PrenosDenarja PrenosDenarja1) {
            this.prenosDenarjaAsync(PrenosDenarja1, null);
        }
        
        /// <remarks/>
        public void prenosDenarjaAsync(PrenosDenarja PrenosDenarja1, object userState) {
            if ((this.prenosDenarjaOperationCompleted == null)) {
                this.prenosDenarjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprenosDenarjaOperationCompleted);
            }
            this.InvokeAsync("prenosDenarja", new object[] {
                        PrenosDenarja1}, this.prenosDenarjaOperationCompleted, userState);
        }
        
        private void OnprenosDenarjaOperationCompleted(object arg) {
            if ((this.prenosDenarjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.prenosDenarjaCompleted(this, new prenosDenarjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Odgovor", Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
        public Odgovor avtomatskoPlacevanjeRacuna([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")] IzdaniRacun IzdaniRacun) {
            object[] results = this.Invoke("avtomatskoPlacevanjeRacuna", new object[] {
                        IzdaniRacun});
            return ((Odgovor)(results[0]));
        }
        
        /// <remarks/>
        public void avtomatskoPlacevanjeRacunaAsync(IzdaniRacun IzdaniRacun) {
            this.avtomatskoPlacevanjeRacunaAsync(IzdaniRacun, null);
        }
        
        /// <remarks/>
        public void avtomatskoPlacevanjeRacunaAsync(IzdaniRacun IzdaniRacun, object userState) {
            if ((this.avtomatskoPlacevanjeRacunaOperationCompleted == null)) {
                this.avtomatskoPlacevanjeRacunaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnavtomatskoPlacevanjeRacunaOperationCompleted);
            }
            this.InvokeAsync("avtomatskoPlacevanjeRacuna", new object[] {
                        IzdaniRacun}, this.avtomatskoPlacevanjeRacunaOperationCompleted, userState);
        }
        
        private void OnavtomatskoPlacevanjeRacunaOperationCompleted(object arg) {
            if ((this.avtomatskoPlacevanjeRacunaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.avtomatskoPlacevanjeRacunaCompleted(this, new avtomatskoPlacevanjeRacunaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Kredit", Namespace="http://www.feri.uni-mb.si/soa/KBP/kredit")]
        public Kredit[] pregledKreditovNaRacunu([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string stevilkaTRR) {
            object[] results = this.Invoke("pregledKreditovNaRacunu", new object[] {
                        stevilkaTRR});
            return ((Kredit[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledKreditovNaRacunuAsync(string stevilkaTRR) {
            this.pregledKreditovNaRacunuAsync(stevilkaTRR, null);
        }
        
        /// <remarks/>
        public void pregledKreditovNaRacunuAsync(string stevilkaTRR, object userState) {
            if ((this.pregledKreditovNaRacunuOperationCompleted == null)) {
                this.pregledKreditovNaRacunuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledKreditovNaRacunuOperationCompleted);
            }
            this.InvokeAsync("pregledKreditovNaRacunu", new object[] {
                        stevilkaTRR}, this.pregledKreditovNaRacunuOperationCompleted, userState);
        }
        
        private void OnpregledKreditovNaRacunuOperationCompleted(object arg) {
            if ((this.pregledKreditovNaRacunuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledKreditovNaRacunuCompleted(this, new pregledKreditovNaRacunuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP/intranet", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP/intranet", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool prijava([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uporabniskoIme, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string geslo) {
            object[] results = this.Invoke("prijava", new object[] {
                        uporabniskoIme,
                        geslo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void prijavaAsync(string uporabniskoIme, string geslo) {
            this.prijavaAsync(uporabniskoIme, geslo, null);
        }
        
        /// <remarks/>
        public void prijavaAsync(string uporabniskoIme, string geslo, object userState) {
            if ((this.prijavaOperationCompleted == null)) {
                this.prijavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprijavaOperationCompleted);
            }
            this.InvokeAsync("prijava", new object[] {
                        uporabniskoIme,
                        geslo}, this.prijavaOperationCompleted, userState);
        }
        
        private void OnprijavaOperationCompleted(object arg) {
            if ((this.prijavaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.prijavaCompleted(this, new prijavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://www.feri.uni-mb.si/soa/KBP", ResponseNamespace="http://www.feri.uni-mb.si/soa/KBP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Odgovor", Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
        public Odgovor placajRacun([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")] IzdaniRacun IzdaniRacun) {
            object[] results = this.Invoke("placajRacun", new object[] {
                        IzdaniRacun});
            return ((Odgovor)(results[0]));
        }
        
        /// <remarks/>
        public void placajRacunAsync(IzdaniRacun IzdaniRacun) {
            this.placajRacunAsync(IzdaniRacun, null);
        }
        
        /// <remarks/>
        public void placajRacunAsync(IzdaniRacun IzdaniRacun, object userState) {
            if ((this.placajRacunOperationCompleted == null)) {
                this.placajRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnplacajRacunOperationCompleted);
            }
            this.InvokeAsync("placajRacun", new object[] {
                        IzdaniRacun}, this.placajRacunOperationCompleted, userState);
        }
        
        private void OnplacajRacunOperationCompleted(object arg) {
            if ((this.placajRacunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.placajRacunCompleted(this, new placajRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacun {
        
        private IzdaniRacunRacun racunField;
        
        /// <remarks/>
        public IzdaniRacunRacun Racun {
            get {
                return this.racunField;
            }
            set {
                this.racunField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacun {
        
        private ushort stevilkaRacunaField;
        
        private System.DateTime datumRacunaField;
        
        private string valutaField;
        
        private string lokacijaField;
        
        private System.DateTime placilniRokField;
        
        private IzdaniRacunRacunIzdajatelj izdajateljField;
        
        private IzdaniRacunRacunPrejemnik prejemnikField;
        
        private IzdaniRacunRacunPostavka[] postavkeRacunaField;
        
        private IzdaniRacunRacunPovzetekZneskovRacuna povzetekZneskovRacunaField;
        
        private IzdaniRacunRacunPlaciloRacuna placiloRacunaField;
        
        /// <remarks/>
        public ushort StevilkaRacuna {
            get {
                return this.stevilkaRacunaField;
            }
            set {
                this.stevilkaRacunaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatumRacuna {
            get {
                return this.datumRacunaField;
            }
            set {
                this.datumRacunaField = value;
            }
        }
        
        /// <remarks/>
        public string Valuta {
            get {
                return this.valutaField;
            }
            set {
                this.valutaField = value;
            }
        }
        
        /// <remarks/>
        public string Lokacija {
            get {
                return this.lokacijaField;
            }
            set {
                this.lokacijaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PlacilniRok {
            get {
                return this.placilniRokField;
            }
            set {
                this.placilniRokField = value;
            }
        }
        
        /// <remarks/>
        public IzdaniRacunRacunIzdajatelj Izdajatelj {
            get {
                return this.izdajateljField;
            }
            set {
                this.izdajateljField = value;
            }
        }
        
        /// <remarks/>
        public IzdaniRacunRacunPrejemnik Prejemnik {
            get {
                return this.prejemnikField;
            }
            set {
                this.prejemnikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Postavka", IsNullable=false)]
        public IzdaniRacunRacunPostavka[] PostavkeRacuna {
            get {
                return this.postavkeRacunaField;
            }
            set {
                this.postavkeRacunaField = value;
            }
        }
        
        /// <remarks/>
        public IzdaniRacunRacunPovzetekZneskovRacuna PovzetekZneskovRacuna {
            get {
                return this.povzetekZneskovRacunaField;
            }
            set {
                this.povzetekZneskovRacunaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IzdaniRacunRacunPlaciloRacuna PlaciloRacuna {
            get {
                return this.placiloRacunaField;
            }
            set {
                this.placiloRacunaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunIzdajatelj {
        
        private IzdaniRacunRacunIzdajateljNazivNaslov nazivNaslovField;
        
        private IzdaniRacunRacunIzdajateljFinancniPodatki financniPodatkiField;
        
        /// <remarks/>
        public IzdaniRacunRacunIzdajateljNazivNaslov NazivNaslov {
            get {
                return this.nazivNaslovField;
            }
            set {
                this.nazivNaslovField = value;
            }
        }
        
        /// <remarks/>
        public IzdaniRacunRacunIzdajateljFinancniPodatki FinancniPodatki {
            get {
                return this.financniPodatkiField;
            }
            set {
                this.financniPodatkiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunIzdajateljNazivNaslov {
        
        private string nazivField;
        
        private string ulicaField;
        
        private string krajField;
        
        private string nazivDrzaveField;
        
        private ushort postnaStevilkaField;
        
        private string kodaDrzaveField;
        
        /// <remarks/>
        public string Naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
            }
        }
        
        /// <remarks/>
        public string Ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        public string Kraj {
            get {
                return this.krajField;
            }
            set {
                this.krajField = value;
            }
        }
        
        /// <remarks/>
        public string NazivDrzave {
            get {
                return this.nazivDrzaveField;
            }
            set {
                this.nazivDrzaveField = value;
            }
        }
        
        /// <remarks/>
        public ushort PostnaStevilka {
            get {
                return this.postnaStevilkaField;
            }
            set {
                this.postnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        public string KodaDrzave {
            get {
                return this.kodaDrzaveField;
            }
            set {
                this.kodaDrzaveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunIzdajateljFinancniPodatki {
        
        private IzdaniRacunRacunIzdajateljFinancniPodatkiBancniRacun bancniRacunField;
        
        /// <remarks/>
        public IzdaniRacunRacunIzdajateljFinancniPodatkiBancniRacun BancniRacun {
            get {
                return this.bancniRacunField;
            }
            set {
                this.bancniRacunField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunIzdajateljFinancniPodatkiBancniRacun {
        
        private string stevilkaBancnegaRacunaField;
        
        private string nazivBankeField;
        
        private string bICField;
        
        /// <remarks/>
        public string StevilkaBancnegaRacuna {
            get {
                return this.stevilkaBancnegaRacunaField;
            }
            set {
                this.stevilkaBancnegaRacunaField = value;
            }
        }
        
        /// <remarks/>
        public string NazivBanke {
            get {
                return this.nazivBankeField;
            }
            set {
                this.nazivBankeField = value;
            }
        }
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPrejemnik {
        
        private IzdaniRacunRacunPrejemnikNazivNaslov nazivNaslovField;
        
        private IzdaniRacunRacunPrejemnikFinancniPodatki financniPodatkiField;
        
        /// <remarks/>
        public IzdaniRacunRacunPrejemnikNazivNaslov NazivNaslov {
            get {
                return this.nazivNaslovField;
            }
            set {
                this.nazivNaslovField = value;
            }
        }
        
        /// <remarks/>
        public IzdaniRacunRacunPrejemnikFinancniPodatki FinancniPodatki {
            get {
                return this.financniPodatkiField;
            }
            set {
                this.financniPodatkiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPrejemnikNazivNaslov {
        
        private string nazivField;
        
        private string ulicaField;
        
        private string krajField;
        
        private string nazivDrzaveField;
        
        private ushort postnaStevilkaField;
        
        private string kodaDrzaveField;
        
        /// <remarks/>
        public string Naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
            }
        }
        
        /// <remarks/>
        public string Ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        public string Kraj {
            get {
                return this.krajField;
            }
            set {
                this.krajField = value;
            }
        }
        
        /// <remarks/>
        public string NazivDrzave {
            get {
                return this.nazivDrzaveField;
            }
            set {
                this.nazivDrzaveField = value;
            }
        }
        
        /// <remarks/>
        public ushort PostnaStevilka {
            get {
                return this.postnaStevilkaField;
            }
            set {
                this.postnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        public string KodaDrzave {
            get {
                return this.kodaDrzaveField;
            }
            set {
                this.kodaDrzaveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPrejemnikFinancniPodatki {
        
        private IzdaniRacunRacunPrejemnikFinancniPodatkiBancniRacun bancniRacunField;
        
        /// <remarks/>
        public IzdaniRacunRacunPrejemnikFinancniPodatkiBancniRacun BancniRacun {
            get {
                return this.bancniRacunField;
            }
            set {
                this.bancniRacunField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPrejemnikFinancniPodatkiBancniRacun {
        
        private string stevilkaBancnegaRacunaField;
        
        private string nazivBankeField;
        
        private string bICField;
        
        /// <remarks/>
        public string StevilkaBancnegaRacuna {
            get {
                return this.stevilkaBancnegaRacunaField;
            }
            set {
                this.stevilkaBancnegaRacunaField = value;
            }
        }
        
        /// <remarks/>
        public string NazivBanke {
            get {
                return this.nazivBankeField;
            }
            set {
                this.nazivBankeField = value;
            }
        }
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPostavka {
        
        private string opisField;
        
        private IzdaniRacunRacunPostavkaKolicinaArtikla kolicinaArtiklaField;
        
        private decimal cenaEnoteField;
        
        private decimal znesekPostavkeField;
        
        private IzdaniRacunRacunPostavkaDavkiNaPostavki davkiNaPostavkiField;
        
        /// <remarks/>
        public string Opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
            }
        }
        
        /// <remarks/>
        public IzdaniRacunRacunPostavkaKolicinaArtikla KolicinaArtikla {
            get {
                return this.kolicinaArtiklaField;
            }
            set {
                this.kolicinaArtiklaField = value;
            }
        }
        
        /// <remarks/>
        public decimal CenaEnote {
            get {
                return this.cenaEnoteField;
            }
            set {
                this.cenaEnoteField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZnesekPostavke {
            get {
                return this.znesekPostavkeField;
            }
            set {
                this.znesekPostavkeField = value;
            }
        }
        
        /// <remarks/>
        public IzdaniRacunRacunPostavkaDavkiNaPostavki DavkiNaPostavki {
            get {
                return this.davkiNaPostavkiField;
            }
            set {
                this.davkiNaPostavkiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPostavkaKolicinaArtikla {
        
        private float kolicinaField;
        
        private string enotaMereField;
        
        /// <remarks/>
        public float Kolicina {
            get {
                return this.kolicinaField;
            }
            set {
                this.kolicinaField = value;
            }
        }
        
        /// <remarks/>
        public string EnotaMere {
            get {
                return this.enotaMereField;
            }
            set {
                this.enotaMereField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPostavkaDavkiNaPostavki {
        
        private decimal odstotekDavkaPostavkeField;
        
        private decimal znesekDavkaPostavkeField;
        
        /// <remarks/>
        public decimal OdstotekDavkaPostavke {
            get {
                return this.odstotekDavkaPostavkeField;
            }
            set {
                this.odstotekDavkaPostavkeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZnesekDavkaPostavke {
            get {
                return this.znesekDavkaPostavkeField;
            }
            set {
                this.znesekDavkaPostavkeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPovzetekZneskovRacuna {
        
        private decimal osnovaZaDavekField;
        
        private decimal davekField;
        
        private decimal znesekRacunaField;
        
        /// <remarks/>
        public decimal OsnovaZaDavek {
            get {
                return this.osnovaZaDavekField;
            }
            set {
                this.osnovaZaDavekField = value;
            }
        }
        
        /// <remarks/>
        public decimal Davek {
            get {
                return this.davekField;
            }
            set {
                this.davekField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZnesekRacuna {
            get {
                return this.znesekRacunaField;
            }
            set {
                this.znesekRacunaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/izdaniRacun")]
    public partial class IzdaniRacunRacunPlaciloRacuna {
        
        private bool opravljenoField;
        
        private System.Nullable<System.DateTime> datumPlacilaField;
        
        /// <remarks/>
        public bool Opravljeno {
            get {
                return this.opravljenoField;
            }
            set {
                this.opravljenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> DatumPlacila {
            get {
                return this.datumPlacilaField;
            }
            set {
                this.datumPlacilaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/odgovor")]
    public partial class Odgovor {
        
        private string statusField;
        
        private string odgovorSifraField;
        
        private bool uspesnoField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string OdgovorSifra {
            get {
                return this.odgovorSifraField;
            }
            set {
                this.odgovorSifraField = value;
            }
        }
        
        /// <remarks/>
        public bool Uspesno {
            get {
                return this.uspesnoField;
            }
            set {
                this.uspesnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/pregledPrometa")]
    public partial class PregledPrometa {
        
        private string stevilkaRacunaField;
        
        private decimal znesekTransakcijeField;
        
        private string valutaTransakcijeField;
        
        private System.DateTime casTransakcijeField;
        
        private string nacinPlacilaField;
        
        private string vrstaTransakcijeField;
        
        private string dodatnoField;
        
        /// <remarks/>
        public string StevilkaRacuna {
            get {
                return this.stevilkaRacunaField;
            }
            set {
                this.stevilkaRacunaField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZnesekTransakcije {
            get {
                return this.znesekTransakcijeField;
            }
            set {
                this.znesekTransakcijeField = value;
            }
        }
        
        /// <remarks/>
        public string ValutaTransakcije {
            get {
                return this.valutaTransakcijeField;
            }
            set {
                this.valutaTransakcijeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CasTransakcije {
            get {
                return this.casTransakcijeField;
            }
            set {
                this.casTransakcijeField = value;
            }
        }
        
        /// <remarks/>
        public string NacinPlacila {
            get {
                return this.nacinPlacilaField;
            }
            set {
                this.nacinPlacilaField = value;
            }
        }
        
        /// <remarks/>
        public string VrstaTransakcije {
            get {
                return this.vrstaTransakcijeField;
            }
            set {
                this.vrstaTransakcijeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dodatno {
            get {
                return this.dodatnoField;
            }
            set {
                this.dodatnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/placiloSKartico")]
    public partial class PlaciloSKartico {
        
        private int stevilkaKarticeField;
        
        private string stevilkaRacunaPrejemnikField;
        
        private decimal znesekPlacilaField;
        
        private string valutaPlacilaField;
        
        private System.DateTime casPlacilaField;
        
        private string lokacijaField;
        
        /// <remarks/>
        public int StevilkaKartice {
            get {
                return this.stevilkaKarticeField;
            }
            set {
                this.stevilkaKarticeField = value;
            }
        }
        
        /// <remarks/>
        public string StevilkaRacunaPrejemnik {
            get {
                return this.stevilkaRacunaPrejemnikField;
            }
            set {
                this.stevilkaRacunaPrejemnikField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZnesekPlacila {
            get {
                return this.znesekPlacilaField;
            }
            set {
                this.znesekPlacilaField = value;
            }
        }
        
        /// <remarks/>
        public string ValutaPlacila {
            get {
                return this.valutaPlacilaField;
            }
            set {
                this.valutaPlacilaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CasPlacila {
            get {
                return this.casPlacilaField;
            }
            set {
                this.casPlacilaField = value;
            }
        }
        
        /// <remarks/>
        public string Lokacija {
            get {
                return this.lokacijaField;
            }
            set {
                this.lokacijaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/prenosDenarja")]
    public partial class PrenosDenarja {
        
        private string stevilkaRacunaPosiljateljField;
        
        private string stevilkaRacunaPrejemnikField;
        
        private decimal znesekPrenosaField;
        
        private string valutaField;
        
        private System.DateTime casPrenosaField;
        
        /// <remarks/>
        public string StevilkaRacunaPosiljatelj {
            get {
                return this.stevilkaRacunaPosiljateljField;
            }
            set {
                this.stevilkaRacunaPosiljateljField = value;
            }
        }
        
        /// <remarks/>
        public string StevilkaRacunaPrejemnik {
            get {
                return this.stevilkaRacunaPrejemnikField;
            }
            set {
                this.stevilkaRacunaPrejemnikField = value;
            }
        }
        
        /// <remarks/>
        public decimal ZnesekPrenosa {
            get {
                return this.znesekPrenosaField;
            }
            set {
                this.znesekPrenosaField = value;
            }
        }
        
        /// <remarks/>
        public string Valuta {
            get {
                return this.valutaField;
            }
            set {
                this.valutaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CasPrenosa {
            get {
                return this.casPrenosaField;
            }
            set {
                this.casPrenosaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.feri.uni-mb.si/soa/KBP/kredit")]
    public partial class Kredit {
        
        private string stevilkaKreditaField;
        
        private double vrednostkreditaField;
        
        private string valutaField;
        
        private decimal obrestnaMeraField;
        
        private string vrstaObrestneMereField;
        
        private System.DateTime datumSklenitveField;
        
        private System.DateTime datumZapadlostiField;
        
        private System.DateTime datumZadnjegaPlacilaField;
        
        private decimal ostanekDolgaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string StevilkaKredita {
            get {
                return this.stevilkaKreditaField;
            }
            set {
                this.stevilkaKreditaField = value;
            }
        }
        
        /// <remarks/>
        public double Vrednostkredita {
            get {
                return this.vrednostkreditaField;
            }
            set {
                this.vrednostkreditaField = value;
            }
        }
        
        /// <remarks/>
        public string Valuta {
            get {
                return this.valutaField;
            }
            set {
                this.valutaField = value;
            }
        }
        
        /// <remarks/>
        public decimal ObrestnaMera {
            get {
                return this.obrestnaMeraField;
            }
            set {
                this.obrestnaMeraField = value;
            }
        }
        
        /// <remarks/>
        public string VrstaObrestneMere {
            get {
                return this.vrstaObrestneMereField;
            }
            set {
                this.vrstaObrestneMereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatumSklenitve {
            get {
                return this.datumSklenitveField;
            }
            set {
                this.datumSklenitveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatumZapadlosti {
            get {
                return this.datumZapadlostiField;
            }
            set {
                this.datumZapadlostiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatumZadnjegaPlacila {
            get {
                return this.datumZadnjegaPlacilaField;
            }
            set {
                this.datumZadnjegaPlacilaField = value;
            }
        }
        
        /// <remarks/>
        public decimal OstanekDolga {
            get {
                return this.ostanekDolgaField;
            }
            set {
                this.ostanekDolgaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void izdajRacunCompletedEventHandler(object sender, izdajRacunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class izdajRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal izdajRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Odgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Odgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledNeplacanihIzdanihRacunovCompletedEventHandler(object sender, pregledNeplacanihIzdanihRacunovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledNeplacanihIzdanihRacunovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledNeplacanihIzdanihRacunovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IzdaniRacun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IzdaniRacun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledPlacanihIzdanihRacunovCompletedEventHandler(object sender, pregledPlacanihIzdanihRacunovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledPlacanihIzdanihRacunovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledPlacanihIzdanihRacunovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IzdaniRacun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IzdaniRacun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void preklicAvtomatskegaPlacevanjaRacunaCompletedEventHandler(object sender, preklicAvtomatskegaPlacevanjaRacunaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class preklicAvtomatskegaPlacevanjaRacunaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal preklicAvtomatskegaPlacevanjaRacunaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Odgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Odgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void preklicNeplacanegaRacunaCompletedEventHandler(object sender, preklicNeplacanegaRacunaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class preklicNeplacanegaRacunaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal preklicNeplacanegaRacunaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Odgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Odgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledPrometaCompletedEventHandler(object sender, pregledPrometaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledPrometaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledPrometaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PregledPrometa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PregledPrometa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledStanjaCompletedEventHandler(object sender, pregledStanjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledStanjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledStanjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledNeplacanihRacunovCompletedEventHandler(object sender, pregledNeplacanihRacunovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledNeplacanihRacunovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledNeplacanihRacunovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IzdaniRacun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IzdaniRacun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledPlacanihRacunovCompletedEventHandler(object sender, pregledPlacanihRacunovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledPlacanihRacunovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledPlacanihRacunovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IzdaniRacun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IzdaniRacun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void placiloSKarticoCompletedEventHandler(object sender, placiloSKarticoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class placiloSKarticoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal placiloSKarticoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Odgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Odgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledPlacilSKarticoCompletedEventHandler(object sender, pregledPlacilSKarticoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledPlacilSKarticoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledPlacilSKarticoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PlaciloSKartico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PlaciloSKartico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void prenosDenarjaCompletedEventHandler(object sender, prenosDenarjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class prenosDenarjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal prenosDenarjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Odgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Odgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void avtomatskoPlacevanjeRacunaCompletedEventHandler(object sender, avtomatskoPlacevanjeRacunaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class avtomatskoPlacevanjeRacunaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal avtomatskoPlacevanjeRacunaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Odgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Odgovor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledKreditovNaRacunuCompletedEventHandler(object sender, pregledKreditovNaRacunuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledKreditovNaRacunuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledKreditovNaRacunuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Kredit[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Kredit[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void prijavaCompletedEventHandler(object sender, prijavaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class prijavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal prijavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void placajRacunCompletedEventHandler(object sender, placajRacunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class placajRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal placajRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Odgovor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Odgovor)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591