//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace TehHotel.Gui.Test.RentACarStrankeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IStranke", Namespace="http://tempuri.org/")]
    public partial class Stranke : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dodajStrankoOperationCompleted;
        
        private System.Threading.SendOrPostCallback odstraniStrankoOperationCompleted;
        
        private System.Threading.SendOrPostCallback spremeniStrankoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pregledVsehStrankOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Stranke() {
            this.Url = global::TehHotel.Gui.Test.Properties.Settings.Default.TehHotel_Gui_Test_RentACarStrankeService_Stranke;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dodajStrankoCompletedEventHandler dodajStrankoCompleted;
        
        /// <remarks/>
        public event odstraniStrankoCompletedEventHandler odstraniStrankoCompleted;
        
        /// <remarks/>
        public event spremeniStrankoCompletedEventHandler spremeniStrankoCompleted;
        
        /// <remarks/>
        public event pregledVsehStrankCompletedEventHandler pregledVsehStrankCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IStranke/dodajStranko", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dodajStranko([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Stranka stranka) {
            object[] results = this.Invoke("dodajStranko", new object[] {
                        stranka});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dodajStrankoAsync(Stranka stranka) {
            this.dodajStrankoAsync(stranka, null);
        }
        
        /// <remarks/>
        public void dodajStrankoAsync(Stranka stranka, object userState) {
            if ((this.dodajStrankoOperationCompleted == null)) {
                this.dodajStrankoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndodajStrankoOperationCompleted);
            }
            this.InvokeAsync("dodajStranko", new object[] {
                        stranka}, this.dodajStrankoOperationCompleted, userState);
        }
        
        private void OndodajStrankoOperationCompleted(object arg) {
            if ((this.dodajStrankoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dodajStrankoCompleted(this, new dodajStrankoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IStranke/odstraniStranko", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string odstraniStranko(int idStranke, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idStrankeSpecified) {
            object[] results = this.Invoke("odstraniStranko", new object[] {
                        idStranke,
                        idStrankeSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void odstraniStrankoAsync(int idStranke, bool idStrankeSpecified) {
            this.odstraniStrankoAsync(idStranke, idStrankeSpecified, null);
        }
        
        /// <remarks/>
        public void odstraniStrankoAsync(int idStranke, bool idStrankeSpecified, object userState) {
            if ((this.odstraniStrankoOperationCompleted == null)) {
                this.odstraniStrankoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnodstraniStrankoOperationCompleted);
            }
            this.InvokeAsync("odstraniStranko", new object[] {
                        idStranke,
                        idStrankeSpecified}, this.odstraniStrankoOperationCompleted, userState);
        }
        
        private void OnodstraniStrankoOperationCompleted(object arg) {
            if ((this.odstraniStrankoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.odstraniStrankoCompleted(this, new odstraniStrankoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IStranke/spremeniStranko", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string spremeniStranko(int idStranka, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idStrankaSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Stranka stranka) {
            object[] results = this.Invoke("spremeniStranko", new object[] {
                        idStranka,
                        idStrankaSpecified,
                        stranka});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void spremeniStrankoAsync(int idStranka, bool idStrankaSpecified, Stranka stranka) {
            this.spremeniStrankoAsync(idStranka, idStrankaSpecified, stranka, null);
        }
        
        /// <remarks/>
        public void spremeniStrankoAsync(int idStranka, bool idStrankaSpecified, Stranka stranka, object userState) {
            if ((this.spremeniStrankoOperationCompleted == null)) {
                this.spremeniStrankoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnspremeniStrankoOperationCompleted);
            }
            this.InvokeAsync("spremeniStranko", new object[] {
                        idStranka,
                        idStrankaSpecified,
                        stranka}, this.spremeniStrankoOperationCompleted, userState);
        }
        
        private void OnspremeniStrankoOperationCompleted(object arg) {
            if ((this.spremeniStrankoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.spremeniStrankoCompleted(this, new spremeniStrankoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IStranke/pregledVsehStrank", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RentACar2_Stranke")]
        public Stranka[] pregledVsehStrank() {
            object[] results = this.Invoke("pregledVsehStrank", new object[0]);
            return ((Stranka[])(results[0]));
        }
        
        /// <remarks/>
        public void pregledVsehStrankAsync() {
            this.pregledVsehStrankAsync(null);
        }
        
        /// <remarks/>
        public void pregledVsehStrankAsync(object userState) {
            if ((this.pregledVsehStrankOperationCompleted == null)) {
                this.pregledVsehStrankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpregledVsehStrankOperationCompleted);
            }
            this.InvokeAsync("pregledVsehStrank", new object[0], this.pregledVsehStrankOperationCompleted, userState);
        }
        
        private void OnpregledVsehStrankOperationCompleted(object arg) {
            if ((this.pregledVsehStrankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pregledVsehStrankCompleted(this, new pregledVsehStrankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RentACar2_Stranke")]
    public partial class Stranka {
        
        private string drzavaField;
        
        private string emailField;
        
        private string emsoField;
        
        private int idstrankaField;
        
        private bool idstrankaFieldSpecified;
        
        private string imeField;
        
        private string krajField;
        
        private int postnaStevilkaField;
        
        private bool postnaStevilkaFieldSpecified;
        
        private string priimekField;
        
        private string telefonField;
        
        private string ulicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Drzava {
            get {
                return this.drzavaField;
            }
            set {
                this.drzavaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Emso {
            get {
                return this.emsoField;
            }
            set {
                this.emsoField = value;
            }
        }
        
        /// <remarks/>
        public int Idstranka {
            get {
                return this.idstrankaField;
            }
            set {
                this.idstrankaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdstrankaSpecified {
            get {
                return this.idstrankaFieldSpecified;
            }
            set {
                this.idstrankaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ime {
            get {
                return this.imeField;
            }
            set {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Kraj {
            get {
                return this.krajField;
            }
            set {
                this.krajField = value;
            }
        }
        
        /// <remarks/>
        public int PostnaStevilka {
            get {
                return this.postnaStevilkaField;
            }
            set {
                this.postnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostnaStevilkaSpecified {
            get {
                return this.postnaStevilkaFieldSpecified;
            }
            set {
                this.postnaStevilkaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Priimek {
            get {
                return this.priimekField;
            }
            set {
                this.priimekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void dodajStrankoCompletedEventHandler(object sender, dodajStrankoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dodajStrankoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dodajStrankoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void odstraniStrankoCompletedEventHandler(object sender, odstraniStrankoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class odstraniStrankoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal odstraniStrankoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void spremeniStrankoCompletedEventHandler(object sender, spremeniStrankoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class spremeniStrankoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal spremeniStrankoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void pregledVsehStrankCompletedEventHandler(object sender, pregledVsehStrankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pregledVsehStrankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pregledVsehStrankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stranka[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stranka[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591