//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TehHotel.TestClient.RemoteStrankaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stranka", Namespace="http//www.tehhotel.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Stranka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumRojstvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.TestClient.RemoteStrankaService.Identifikacija IdentifikacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.TestClient.RemoteStrankaService.Naslov NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRojstva {
            get {
                return this.DatumRojstvaField;
            }
            set {
                if ((this.DatumRojstvaField.Equals(value) != true)) {
                    this.DatumRojstvaField = value;
                    this.RaisePropertyChanged("DatumRojstva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.TestClient.RemoteStrankaService.Identifikacija Identifikacija {
            get {
                return this.IdentifikacijaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifikacijaField, value) != true)) {
                    this.IdentifikacijaField = value;
                    this.RaisePropertyChanged("Identifikacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.TestClient.RemoteStrankaService.Naslov Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identifikacija", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Identifikacija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VrednostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip {
            get {
                return this.TipField;
            }
            set {
                if ((object.ReferenceEquals(this.TipField, value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vrednost {
            get {
                return this.VrednostField;
            }
            set {
                if ((object.ReferenceEquals(this.VrednostField, value) != true)) {
                    this.VrednostField = value;
                    this.RaisePropertyChanged("Vrednost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Naslov", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Naslov : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KrajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnaStevilkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drzava {
            get {
                return this.DrzavaField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaField, value) != true)) {
                    this.DrzavaField = value;
                    this.RaisePropertyChanged("Drzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kraj {
            get {
                return this.KrajField;
            }
            set {
                if ((object.ReferenceEquals(this.KrajField, value) != true)) {
                    this.KrajField = value;
                    this.RaisePropertyChanged("Kraj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostnaStevilka {
            get {
                return this.PostnaStevilkaField;
            }
            set {
                if ((this.PostnaStevilkaField.Equals(value) != true)) {
                    this.PostnaStevilkaField = value;
                    this.RaisePropertyChanged("PostnaStevilka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica {
            get {
                return this.UlicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UlicaField, value) != true)) {
                    this.UlicaField = value;
                    this.RaisePropertyChanged("Ulica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http//www.tehhotel.com/", ConfigurationName="RemoteStrankaService.StrankaService")]
    public interface StrankaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/CreateStranka", ReplyAction="http//www.tehhotel.com/StrankaService/CreateStrankaResponse")]
        bool CreateStranka(TehHotel.TestClient.RemoteStrankaService.Stranka s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/CreateStranka", ReplyAction="http//www.tehhotel.com/StrankaService/CreateStrankaResponse")]
        System.Threading.Tasks.Task<bool> CreateStrankaAsync(TehHotel.TestClient.RemoteStrankaService.Stranka s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/ReadStranka", ReplyAction="http//www.tehhotel.com/StrankaService/ReadStrankaResponse")]
        TehHotel.TestClient.RemoteStrankaService.Stranka ReadStranka(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/ReadStranka", ReplyAction="http//www.tehhotel.com/StrankaService/ReadStrankaResponse")]
        System.Threading.Tasks.Task<TehHotel.TestClient.RemoteStrankaService.Stranka> ReadStrankaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/UpdateStranka", ReplyAction="http//www.tehhotel.com/StrankaService/UpdateStrankaResponse")]
        bool UpdateStranka(TehHotel.TestClient.RemoteStrankaService.Stranka s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/UpdateStranka", ReplyAction="http//www.tehhotel.com/StrankaService/UpdateStrankaResponse")]
        System.Threading.Tasks.Task<bool> UpdateStrankaAsync(TehHotel.TestClient.RemoteStrankaService.Stranka s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/DeleteStranka", ReplyAction="http//www.tehhotel.com/StrankaService/DeleteStrankaResponse")]
        bool DeleteStranka(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/DeleteStranka", ReplyAction="http//www.tehhotel.com/StrankaService/DeleteStrankaResponse")]
        System.Threading.Tasks.Task<bool> DeleteStrankaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/ListStranka", ReplyAction="http//www.tehhotel.com/StrankaService/ListStrankaResponse")]
        TehHotel.TestClient.RemoteStrankaService.Stranka[] ListStranka();
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/ListStranka", ReplyAction="http//www.tehhotel.com/StrankaService/ListStrankaResponse")]
        System.Threading.Tasks.Task<TehHotel.TestClient.RemoteStrankaService.Stranka[]> ListStrankaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/CreateStrankaReturnId", ReplyAction="http//www.tehhotel.com/StrankaService/CreateStrankaReturnIdResponse")]
        int CreateStrankaReturnId(TehHotel.TestClient.RemoteStrankaService.Stranka s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/CreateStrankaReturnId", ReplyAction="http//www.tehhotel.com/StrankaService/CreateStrankaReturnIdResponse")]
        System.Threading.Tasks.Task<int> CreateStrankaReturnIdAsync(TehHotel.TestClient.RemoteStrankaService.Stranka s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/IsciStranka", ReplyAction="http//www.tehhotel.com/StrankaService/IsciStrankaResponse")]
        TehHotel.TestClient.RemoteStrankaService.Stranka IsciStranka(string IdentifikacijaTip, string IdentifikacijaVrednost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/StrankaService/IsciStranka", ReplyAction="http//www.tehhotel.com/StrankaService/IsciStrankaResponse")]
        System.Threading.Tasks.Task<TehHotel.TestClient.RemoteStrankaService.Stranka> IsciStrankaAsync(string IdentifikacijaTip, string IdentifikacijaVrednost);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StrankaServiceChannel : TehHotel.TestClient.RemoteStrankaService.StrankaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StrankaServiceClient : System.ServiceModel.ClientBase<TehHotel.TestClient.RemoteStrankaService.StrankaService>, TehHotel.TestClient.RemoteStrankaService.StrankaService {
        
        public StrankaServiceClient() {
        }
        
        public StrankaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StrankaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrankaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrankaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateStranka(TehHotel.TestClient.RemoteStrankaService.Stranka s) {
            return base.Channel.CreateStranka(s);
        }
        
        public System.Threading.Tasks.Task<bool> CreateStrankaAsync(TehHotel.TestClient.RemoteStrankaService.Stranka s) {
            return base.Channel.CreateStrankaAsync(s);
        }
        
        public TehHotel.TestClient.RemoteStrankaService.Stranka ReadStranka(int id) {
            return base.Channel.ReadStranka(id);
        }
        
        public System.Threading.Tasks.Task<TehHotel.TestClient.RemoteStrankaService.Stranka> ReadStrankaAsync(int id) {
            return base.Channel.ReadStrankaAsync(id);
        }
        
        public bool UpdateStranka(TehHotel.TestClient.RemoteStrankaService.Stranka s) {
            return base.Channel.UpdateStranka(s);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStrankaAsync(TehHotel.TestClient.RemoteStrankaService.Stranka s) {
            return base.Channel.UpdateStrankaAsync(s);
        }
        
        public bool DeleteStranka(int id) {
            return base.Channel.DeleteStranka(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStrankaAsync(int id) {
            return base.Channel.DeleteStrankaAsync(id);
        }
        
        public TehHotel.TestClient.RemoteStrankaService.Stranka[] ListStranka() {
            return base.Channel.ListStranka();
        }
        
        public System.Threading.Tasks.Task<TehHotel.TestClient.RemoteStrankaService.Stranka[]> ListStrankaAsync() {
            return base.Channel.ListStrankaAsync();
        }
        
        public int CreateStrankaReturnId(TehHotel.TestClient.RemoteStrankaService.Stranka s) {
            return base.Channel.CreateStrankaReturnId(s);
        }
        
        public System.Threading.Tasks.Task<int> CreateStrankaReturnIdAsync(TehHotel.TestClient.RemoteStrankaService.Stranka s) {
            return base.Channel.CreateStrankaReturnIdAsync(s);
        }
        
        public TehHotel.TestClient.RemoteStrankaService.Stranka IsciStranka(string IdentifikacijaTip, string IdentifikacijaVrednost) {
            return base.Channel.IsciStranka(IdentifikacijaTip, IdentifikacijaVrednost);
        }
        
        public System.Threading.Tasks.Task<TehHotel.TestClient.RemoteStrankaService.Stranka> IsciStrankaAsync(string IdentifikacijaTip, string IdentifikacijaVrednost) {
            return base.Channel.IsciStrankaAsync(IdentifikacijaTip, IdentifikacijaVrednost);
        }
    }
}
