//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TehHotel.Gui.Test.RezervacijaServiceSecure {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RezervacijaSobe", Namespace="http://schemas.datacontract.org/2004/07/TehHotel.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class RezervacijaSobe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumDoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumOdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Hotel HotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HranaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RezervacijaSobeMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Soba SobaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka StrankaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumDo {
            get {
                return this.DatumDoField;
            }
            set {
                if ((this.DatumDoField.Equals(value) != true)) {
                    this.DatumDoField = value;
                    this.RaisePropertyChanged("DatumDo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumOd {
            get {
                return this.DatumOdField;
            }
            set {
                if ((this.DatumOdField.Equals(value) != true)) {
                    this.DatumOdField = value;
                    this.RaisePropertyChanged("DatumOd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Hotel Hotel {
            get {
                return this.HotelField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelField, value) != true)) {
                    this.HotelField = value;
                    this.RaisePropertyChanged("Hotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hrana {
            get {
                return this.HranaField;
            }
            set {
                if ((object.ReferenceEquals(this.HranaField, value) != true)) {
                    this.HranaField = value;
                    this.RaisePropertyChanged("Hrana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="RezervacijaSobe")]
        public int RezervacijaSobeMember {
            get {
                return this.RezervacijaSobeMemberField;
            }
            set {
                if ((this.RezervacijaSobeMemberField.Equals(value) != true)) {
                    this.RezervacijaSobeMemberField = value;
                    this.RaisePropertyChanged("RezervacijaSobeMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Soba Soba {
            get {
                return this.SobaField;
            }
            set {
                if ((object.ReferenceEquals(this.SobaField, value) != true)) {
                    this.SobaField = value;
                    this.RaisePropertyChanged("Soba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka Stranka {
            get {
                return this.StrankaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrankaField, value) != true)) {
                    this.StrankaField = value;
                    this.RaisePropertyChanged("Stranka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BazenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana[] DvoraneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdHotelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KuhinjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Naslov NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Zaposleni[] OsebjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce[] ParkiriscaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Soba[] SobeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZvezdiceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bazen {
            get {
                return this.BazenField;
            }
            set {
                if ((this.BazenField.Equals(value) != true)) {
                    this.BazenField = value;
                    this.RaisePropertyChanged("Bazen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana[] Dvorane {
            get {
                return this.DvoraneField;
            }
            set {
                if ((object.ReferenceEquals(this.DvoraneField, value) != true)) {
                    this.DvoraneField = value;
                    this.RaisePropertyChanged("Dvorane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHotel {
            get {
                return this.IdHotelField;
            }
            set {
                if ((this.IdHotelField.Equals(value) != true)) {
                    this.IdHotelField = value;
                    this.RaisePropertyChanged("IdHotel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kuhinja {
            get {
                return this.KuhinjaField;
            }
            set {
                if ((this.KuhinjaField.Equals(value) != true)) {
                    this.KuhinjaField = value;
                    this.RaisePropertyChanged("Kuhinja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Naslov Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Zaposleni[] Osebje {
            get {
                return this.OsebjeField;
            }
            set {
                if ((object.ReferenceEquals(this.OsebjeField, value) != true)) {
                    this.OsebjeField = value;
                    this.RaisePropertyChanged("Osebje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce[] Parkirisca {
            get {
                return this.ParkiriscaField;
            }
            set {
                if ((object.ReferenceEquals(this.ParkiriscaField, value) != true)) {
                    this.ParkiriscaField = value;
                    this.RaisePropertyChanged("Parkirisca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Soba[] Sobe {
            get {
                return this.SobeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobeField, value) != true)) {
                    this.SobeField = value;
                    this.RaisePropertyChanged("Sobe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Zvezdice {
            get {
                return this.ZvezdiceField;
            }
            set {
                if ((this.ZvezdiceField.Equals(value) != true)) {
                    this.ZvezdiceField = value;
                    this.RaisePropertyChanged("Zvezdice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soba", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Soba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BalkonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HladilnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSobaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InternetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NadstropjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StPosteljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StevilkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TelevizijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Balkon {
            get {
                return this.BalkonField;
            }
            set {
                if ((this.BalkonField.Equals(value) != true)) {
                    this.BalkonField = value;
                    this.RaisePropertyChanged("Balkon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hladilnik {
            get {
                return this.HladilnikField;
            }
            set {
                if ((this.HladilnikField.Equals(value) != true)) {
                    this.HladilnikField = value;
                    this.RaisePropertyChanged("Hladilnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoba {
            get {
                return this.IdSobaField;
            }
            set {
                if ((this.IdSobaField.Equals(value) != true)) {
                    this.IdSobaField = value;
                    this.RaisePropertyChanged("IdSoba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Internet {
            get {
                return this.InternetField;
            }
            set {
                if ((this.InternetField.Equals(value) != true)) {
                    this.InternetField = value;
                    this.RaisePropertyChanged("Internet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nadstropje {
            get {
                return this.NadstropjeField;
            }
            set {
                if ((this.NadstropjeField.Equals(value) != true)) {
                    this.NadstropjeField = value;
                    this.RaisePropertyChanged("Nadstropje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StPostelj {
            get {
                return this.StPosteljField;
            }
            set {
                if ((this.StPosteljField.Equals(value) != true)) {
                    this.StPosteljField = value;
                    this.RaisePropertyChanged("StPostelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stevilka {
            get {
                return this.StevilkaField;
            }
            set {
                if ((this.StevilkaField.Equals(value) != true)) {
                    this.StevilkaField = value;
                    this.RaisePropertyChanged("Stevilka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Televizija {
            get {
                return this.TelevizijaField;
            }
            set {
                if ((this.TelevizijaField.Equals(value) != true)) {
                    this.TelevizijaField = value;
                    this.RaisePropertyChanged("Televizija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valuta {
            get {
                return this.ValutaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValutaField, value) != true)) {
                    this.ValutaField = value;
                    this.RaisePropertyChanged("Valuta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stranka", Namespace="http//www.tehhotel.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Stranka : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumRojstvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdStrankaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Identifikacija IdentifikacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Naslov NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRojstva {
            get {
                return this.DatumRojstvaField;
            }
            set {
                if ((this.DatumRojstvaField.Equals(value) != true)) {
                    this.DatumRojstvaField = value;
                    this.RaisePropertyChanged("DatumRojstva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdStranka {
            get {
                return this.IdStrankaField;
            }
            set {
                if ((this.IdStrankaField.Equals(value) != true)) {
                    this.IdStrankaField = value;
                    this.RaisePropertyChanged("IdStranka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Identifikacija Identifikacija {
            get {
                return this.IdentifikacijaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifikacijaField, value) != true)) {
                    this.IdentifikacijaField = value;
                    this.RaisePropertyChanged("Identifikacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Naslov Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Naslov", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Naslov : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KrajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostnaStevilkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drzava {
            get {
                return this.DrzavaField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaField, value) != true)) {
                    this.DrzavaField = value;
                    this.RaisePropertyChanged("Drzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNaslov {
            get {
                return this.IdNaslovField;
            }
            set {
                if ((this.IdNaslovField.Equals(value) != true)) {
                    this.IdNaslovField = value;
                    this.RaisePropertyChanged("IdNaslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kraj {
            get {
                return this.KrajField;
            }
            set {
                if ((object.ReferenceEquals(this.KrajField, value) != true)) {
                    this.KrajField = value;
                    this.RaisePropertyChanged("Kraj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostnaStevilka {
            get {
                return this.PostnaStevilkaField;
            }
            set {
                if ((this.PostnaStevilkaField.Equals(value) != true)) {
                    this.PostnaStevilkaField = value;
                    this.RaisePropertyChanged("PostnaStevilka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica {
            get {
                return this.UlicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UlicaField, value) != true)) {
                    this.UlicaField = value;
                    this.RaisePropertyChanged("Ulica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dvorana", Namespace="http//www.tehhotel.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Dvorana : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDvoranaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PovrsinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StLjudiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDvorana {
            get {
                return this.IdDvoranaField;
            }
            set {
                if ((this.IdDvoranaField.Equals(value) != true)) {
                    this.IdDvoranaField = value;
                    this.RaisePropertyChanged("IdDvorana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Povrsina {
            get {
                return this.PovrsinaField;
            }
            set {
                if ((this.PovrsinaField.Equals(value) != true)) {
                    this.PovrsinaField = value;
                    this.RaisePropertyChanged("Povrsina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StLjudi {
            get {
                return this.StLjudiField;
            }
            set {
                if ((this.StLjudiField.Equals(value) != true)) {
                    this.StLjudiField = value;
                    this.RaisePropertyChanged("StLjudi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zaposleni", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Zaposleni : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumRojstvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatumZaposlitveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdZaposleniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Identifikacija IdentifikacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IzobrazbaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Naslov NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VlogaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatumRojstva {
            get {
                return this.DatumRojstvaField;
            }
            set {
                if ((this.DatumRojstvaField.Equals(value) != true)) {
                    this.DatumRojstvaField = value;
                    this.RaisePropertyChanged("DatumRojstva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatumZaposlitve {
            get {
                return this.DatumZaposlitveField;
            }
            set {
                if ((this.DatumZaposlitveField.Equals(value) != true)) {
                    this.DatumZaposlitveField = value;
                    this.RaisePropertyChanged("DatumZaposlitve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdZaposleni {
            get {
                return this.IdZaposleniField;
            }
            set {
                if ((this.IdZaposleniField.Equals(value) != true)) {
                    this.IdZaposleniField = value;
                    this.RaisePropertyChanged("IdZaposleni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Identifikacija Identifikacija {
            get {
                return this.IdentifikacijaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifikacijaField, value) != true)) {
                    this.IdentifikacijaField = value;
                    this.RaisePropertyChanged("Identifikacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Izobrazba {
            get {
                return this.IzobrazbaField;
            }
            set {
                if ((object.ReferenceEquals(this.IzobrazbaField, value) != true)) {
                    this.IzobrazbaField = value;
                    this.RaisePropertyChanged("Izobrazba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Naslov Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spol {
            get {
                return this.SpolField;
            }
            set {
                if ((object.ReferenceEquals(this.SpolField, value) != true)) {
                    this.SpolField = value;
                    this.RaisePropertyChanged("Spol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((this.TelefonField.Equals(value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vloga {
            get {
                return this.VlogaField;
            }
            set {
                if ((object.ReferenceEquals(this.VlogaField, value) != true)) {
                    this.VlogaField = value;
                    this.RaisePropertyChanged("Vloga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parkirisce", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Parkirisce : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdParkirisceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PokritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StevilkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdParkirisce {
            get {
                return this.IdParkirisceField;
            }
            set {
                if ((this.IdParkirisceField.Equals(value) != true)) {
                    this.IdParkirisceField = value;
                    this.RaisePropertyChanged("IdParkirisce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pokrito {
            get {
                return this.PokritoField;
            }
            set {
                if ((this.PokritoField.Equals(value) != true)) {
                    this.PokritoField = value;
                    this.RaisePropertyChanged("Pokrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stevilka {
            get {
                return this.StevilkaField;
            }
            set {
                if ((object.ReferenceEquals(this.StevilkaField, value) != true)) {
                    this.StevilkaField = value;
                    this.RaisePropertyChanged("Stevilka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identifikacija", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Identifikacija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdIdentifikacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VrednostField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdIdentifikacija {
            get {
                return this.IdIdentifikacijaField;
            }
            set {
                if ((this.IdIdentifikacijaField.Equals(value) != true)) {
                    this.IdIdentifikacijaField = value;
                    this.RaisePropertyChanged("IdIdentifikacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip {
            get {
                return this.TipField;
            }
            set {
                if ((object.ReferenceEquals(this.TipField, value) != true)) {
                    this.TipField = value;
                    this.RaisePropertyChanged("Tip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vrednost {
            get {
                return this.VrednostField;
            }
            set {
                if ((object.ReferenceEquals(this.VrednostField, value) != true)) {
                    this.VrednostField = value;
                    this.RaisePropertyChanged("Vrednost");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rezervacije", Namespace="http//www.tehhotel.com/")]
    [System.SerializableAttribute()]
    public partial class Rezervacije : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaDvorane[] RezervacijeDvoraneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaParkirisca[] RezervacijeParkiriscaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaDvorane[] RezervacijeDvorane {
            get {
                return this.RezervacijeDvoraneField;
            }
            set {
                if ((object.ReferenceEquals(this.RezervacijeDvoraneField, value) != true)) {
                    this.RezervacijeDvoraneField = value;
                    this.RaisePropertyChanged("RezervacijeDvorane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaParkirisca[] RezervacijeParkirisca {
            get {
                return this.RezervacijeParkiriscaField;
            }
            set {
                if ((object.ReferenceEquals(this.RezervacijeParkiriscaField, value) != true)) {
                    this.RezervacijeParkiriscaField = value;
                    this.RaisePropertyChanged("RezervacijeParkirisca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RezervacijaDvorane", Namespace="http//www.tehhotel.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class RezervacijaDvorane : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumDoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumOdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana DvoranaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRezervacijaDvoraneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImePosebneStoritveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SteviloLjudiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka StrankaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumDo {
            get {
                return this.DatumDoField;
            }
            set {
                if ((this.DatumDoField.Equals(value) != true)) {
                    this.DatumDoField = value;
                    this.RaisePropertyChanged("DatumDo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumOd {
            get {
                return this.DatumOdField;
            }
            set {
                if ((this.DatumOdField.Equals(value) != true)) {
                    this.DatumOdField = value;
                    this.RaisePropertyChanged("DatumOd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana Dvorana {
            get {
                return this.DvoranaField;
            }
            set {
                if ((object.ReferenceEquals(this.DvoranaField, value) != true)) {
                    this.DvoranaField = value;
                    this.RaisePropertyChanged("Dvorana");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRezervacijaDvorane {
            get {
                return this.IdRezervacijaDvoraneField;
            }
            set {
                if ((this.IdRezervacijaDvoraneField.Equals(value) != true)) {
                    this.IdRezervacijaDvoraneField = value;
                    this.RaisePropertyChanged("IdRezervacijaDvorane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImePosebneStoritve {
            get {
                return this.ImePosebneStoritveField;
            }
            set {
                if ((object.ReferenceEquals(this.ImePosebneStoritveField, value) != true)) {
                    this.ImePosebneStoritveField = value;
                    this.RaisePropertyChanged("ImePosebneStoritve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SteviloLjudi {
            get {
                return this.SteviloLjudiField;
            }
            set {
                if ((this.SteviloLjudiField.Equals(value) != true)) {
                    this.SteviloLjudiField = value;
                    this.RaisePropertyChanged("SteviloLjudi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka Stranka {
            get {
                return this.StrankaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrankaField, value) != true)) {
                    this.StrankaField = value;
                    this.RaisePropertyChanged("Stranka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RezervacijaParkirisca", Namespace="http//www.tehhotel.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class RezervacijaParkirisca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumDoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumOdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImePosebneStoritveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce ParkirisceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RezervacijaParkiriscaMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka StrankaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumDo {
            get {
                return this.DatumDoField;
            }
            set {
                if ((this.DatumDoField.Equals(value) != true)) {
                    this.DatumDoField = value;
                    this.RaisePropertyChanged("DatumDo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumOd {
            get {
                return this.DatumOdField;
            }
            set {
                if ((this.DatumOdField.Equals(value) != true)) {
                    this.DatumOdField = value;
                    this.RaisePropertyChanged("DatumOd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImePosebneStoritve {
            get {
                return this.ImePosebneStoritveField;
            }
            set {
                if ((object.ReferenceEquals(this.ImePosebneStoritveField, value) != true)) {
                    this.ImePosebneStoritveField = value;
                    this.RaisePropertyChanged("ImePosebneStoritve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce Parkirisce {
            get {
                return this.ParkirisceField;
            }
            set {
                if ((object.ReferenceEquals(this.ParkirisceField, value) != true)) {
                    this.ParkirisceField = value;
                    this.RaisePropertyChanged("Parkirisce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="RezervacijaParkirisca")]
        public int RezervacijaParkiriscaMember {
            get {
                return this.RezervacijaParkiriscaMemberField;
            }
            set {
                if ((this.RezervacijaParkiriscaMemberField.Equals(value) != true)) {
                    this.RezervacijaParkiriscaMemberField = value;
                    this.RaisePropertyChanged("RezervacijaParkiriscaMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka Stranka {
            get {
                return this.StrankaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrankaField, value) != true)) {
                    this.StrankaField = value;
                    this.RaisePropertyChanged("Stranka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Racun", Namespace="http//www.tehhotel.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Racun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRacunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PlacanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaDvorane[] RezervacijeDvoraneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaParkirisca[] RezervacijeParkiriscaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaSobe[] RezervacijeSobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SkupnaCenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StevilkaRacunaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka StrankaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRacuna {
            get {
                return this.DatumRacunaField;
            }
            set {
                if ((this.DatumRacunaField.Equals(value) != true)) {
                    this.DatumRacunaField = value;
                    this.RaisePropertyChanged("DatumRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRacun {
            get {
                return this.IdRacunField;
            }
            set {
                if ((this.IdRacunField.Equals(value) != true)) {
                    this.IdRacunField = value;
                    this.RaisePropertyChanged("IdRacun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Placano {
            get {
                return this.PlacanoField;
            }
            set {
                if ((this.PlacanoField.Equals(value) != true)) {
                    this.PlacanoField = value;
                    this.RaisePropertyChanged("Placano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaDvorane[] RezervacijeDvorane {
            get {
                return this.RezervacijeDvoraneField;
            }
            set {
                if ((object.ReferenceEquals(this.RezervacijeDvoraneField, value) != true)) {
                    this.RezervacijeDvoraneField = value;
                    this.RaisePropertyChanged("RezervacijeDvorane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaParkirisca[] RezervacijeParkirisca {
            get {
                return this.RezervacijeParkiriscaField;
            }
            set {
                if ((object.ReferenceEquals(this.RezervacijeParkiriscaField, value) != true)) {
                    this.RezervacijeParkiriscaField = value;
                    this.RaisePropertyChanged("RezervacijeParkirisca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaSobe[] RezervacijeSob {
            get {
                return this.RezervacijeSobField;
            }
            set {
                if ((object.ReferenceEquals(this.RezervacijeSobField, value) != true)) {
                    this.RezervacijeSobField = value;
                    this.RaisePropertyChanged("RezervacijeSob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SkupnaCena {
            get {
                return this.SkupnaCenaField;
            }
            set {
                if ((this.SkupnaCenaField.Equals(value) != true)) {
                    this.SkupnaCenaField = value;
                    this.RaisePropertyChanged("SkupnaCena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StevilkaRacuna {
            get {
                return this.StevilkaRacunaField;
            }
            set {
                if ((this.StevilkaRacunaField.Equals(value) != true)) {
                    this.StevilkaRacunaField = value;
                    this.RaisePropertyChanged("StevilkaRacuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Stranka Stranka {
            get {
                return this.StrankaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrankaField, value) != true)) {
                    this.StrankaField = value;
                    this.RaisePropertyChanged("Stranka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valuta {
            get {
                return this.ValutaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValutaField, value) != true)) {
                    this.ValutaField = value;
                    this.RaisePropertyChanged("Valuta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterOptionsSoba", Namespace="http//www.tehhotel.com/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class FilterOptionsSoba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> BalkonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HladilnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> InternetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NadstropjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StPosteljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TelevizijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZvezdiceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Balkon {
            get {
                return this.BalkonField;
            }
            set {
                if ((this.BalkonField.Equals(value) != true)) {
                    this.BalkonField = value;
                    this.RaisePropertyChanged("Balkon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Hladilnik {
            get {
                return this.HladilnikField;
            }
            set {
                if ((this.HladilnikField.Equals(value) != true)) {
                    this.HladilnikField = value;
                    this.RaisePropertyChanged("Hladilnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Internet {
            get {
                return this.InternetField;
            }
            set {
                if ((this.InternetField.Equals(value) != true)) {
                    this.InternetField = value;
                    this.RaisePropertyChanged("Internet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Nadstropje {
            get {
                return this.NadstropjeField;
            }
            set {
                if ((this.NadstropjeField.Equals(value) != true)) {
                    this.NadstropjeField = value;
                    this.RaisePropertyChanged("Nadstropje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StPostelj {
            get {
                return this.StPosteljField;
            }
            set {
                if ((this.StPosteljField.Equals(value) != true)) {
                    this.StPosteljField = value;
                    this.RaisePropertyChanged("StPostelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Televizija {
            get {
                return this.TelevizijaField;
            }
            set {
                if ((this.TelevizijaField.Equals(value) != true)) {
                    this.TelevizijaField = value;
                    this.RaisePropertyChanged("Televizija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Zvezdice {
            get {
                return this.ZvezdiceField;
            }
            set {
                if ((this.ZvezdiceField.Equals(value) != true)) {
                    this.ZvezdiceField = value;
                    this.RaisePropertyChanged("Zvezdice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http//www.tehhotel.com/", ConfigurationName="RezervacijaServiceSecure.RezervacijaService")]
    public interface RezervacijaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/CreateRezervacija", ReplyAction="http//www.tehhotel.com/RezervacijaService/CreateRezervacijaResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Racun CreateRezervacija(int idStranka, int hotelid, TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaSobe[] rezervacijeSobe, TehHotel.Gui.Test.RezervacijaServiceSecure.Rezervacije posebneRezervacije);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/CreateRezervacija", ReplyAction="http//www.tehhotel.com/RezervacijaService/CreateRezervacijaResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun> CreateRezervacijaAsync(int idStranka, int hotelid, TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaSobe[] rezervacijeSobe, TehHotel.Gui.Test.RezervacijaServiceSecure.Rezervacije posebneRezervacije);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRacunResponse")]
        bool DeleteRacun(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRacunResponse")]
        System.Threading.Tasks.Task<bool> DeleteRacunAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaSobe", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaSobeResponse")]
        bool DeleteRezervacijaSobe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaSobe", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaSobeResponse")]
        System.Threading.Tasks.Task<bool> DeleteRezervacijaSobeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaDvorane", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaDvoraneResponse")]
        bool DeleteRezervacijaDvorane(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaDvorane", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaDvoraneResponse")]
        System.Threading.Tasks.Task<bool> DeleteRezervacijaDvoraneAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaParkirisca", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaParkiriscaResponse")]
        bool DeleteRezervacijaParkirisca(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaParkirisca", ReplyAction="http//www.tehhotel.com/RezervacijaService/DeleteRezervacijaParkiriscaResponse")]
        System.Threading.Tasks.Task<bool> DeleteRezervacijaParkiriscaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListRacunResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[] ListRacun(int idStranka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListRacunResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[]> ListRacunAsync(int idStranka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListRacunNeplacani", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListRacunNeplacaniResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[] ListRacunNeplacani(int idStranka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListRacunNeplacani", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListRacunNeplacaniResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[]> ListRacunNeplacaniAsync(int idStranka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/PlacajRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/PlacajRacunResponse")]
        bool PlacajRacun(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/PlacajRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/PlacajRacunResponse")]
        System.Threading.Tasks.Task<bool> PlacajRacunAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeSobe", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeSobeResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Soba[] ListMozneRezervacijeSobe(int idHotel, System.DateTime datumOd, System.DateTime datumDo, TehHotel.Gui.Test.RezervacijaServiceSecure.FilterOptionsSoba fos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeSobe", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeSobeResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Soba[]> ListMozneRezervacijeSobeAsync(int idHotel, System.DateTime datumOd, System.DateTime datumDo, TehHotel.Gui.Test.RezervacijaServiceSecure.FilterOptionsSoba fos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeDvorane", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeDvoraneResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana[] ListMozneRezervacijeDvorane(int idHotel, System.DateTime datumOd, System.DateTime datumDo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeDvorane", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeDvoraneResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana[]> ListMozneRezervacijeDvoraneAsync(int idHotel, System.DateTime datumOd, System.DateTime datumDo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeParkirisca", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeParkiriscaResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce[] ListMozneRezervacijeParkirisca(int idHotel, System.DateTime datumOd, System.DateTime datumDo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeParkirisca", ReplyAction="http//www.tehhotel.com/RezervacijaService/ListMozneRezervacijeParkiriscaResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce[]> ListMozneRezervacijeParkiriscaAsync(int idHotel, System.DateTime datumOd, System.DateTime datumDo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadRacunResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Racun ReadRacun(int Racunid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadRacun", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadRacunResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun> ReadRacunAsync(int Racunid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadRacunStranka", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadRacunStrankaResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Racun ReadRacunStranka(int StrankaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadRacunStranka", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadRacunStrankaResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun> ReadRacunStrankaAsync(int StrankaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadSoba", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadSobaResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Soba ReadSoba(int SobaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadSoba", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadSobaResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Soba> ReadSobaAsync(int SobaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadDvorana", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadDvoranaResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana ReadDvorana(int DvoranaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadDvorana", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadDvoranaResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana> ReadDvoranaAsync(int DvoranaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadParkirisce", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadParkirisceResponse")]
        TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce ReadParkirisce(int ParkirisceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http//www.tehhotel.com/RezervacijaService/ReadParkirisce", ReplyAction="http//www.tehhotel.com/RezervacijaService/ReadParkirisceResponse")]
        System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce> ReadParkirisceAsync(int ParkirisceId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RezervacijaServiceChannel : TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RezervacijaServiceClient : System.ServiceModel.ClientBase<TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaService>, TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaService {
        
        public RezervacijaServiceClient() {
        }
        
        public RezervacijaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RezervacijaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RezervacijaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RezervacijaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Racun CreateRezervacija(int idStranka, int hotelid, TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaSobe[] rezervacijeSobe, TehHotel.Gui.Test.RezervacijaServiceSecure.Rezervacije posebneRezervacije) {
            return base.Channel.CreateRezervacija(idStranka, hotelid, rezervacijeSobe, posebneRezervacije);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun> CreateRezervacijaAsync(int idStranka, int hotelid, TehHotel.Gui.Test.RezervacijaServiceSecure.RezervacijaSobe[] rezervacijeSobe, TehHotel.Gui.Test.RezervacijaServiceSecure.Rezervacije posebneRezervacije) {
            return base.Channel.CreateRezervacijaAsync(idStranka, hotelid, rezervacijeSobe, posebneRezervacije);
        }
        
        public bool DeleteRacun(int id) {
            return base.Channel.DeleteRacun(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRacunAsync(int id) {
            return base.Channel.DeleteRacunAsync(id);
        }
        
        public bool DeleteRezervacijaSobe(int id) {
            return base.Channel.DeleteRezervacijaSobe(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRezervacijaSobeAsync(int id) {
            return base.Channel.DeleteRezervacijaSobeAsync(id);
        }
        
        public bool DeleteRezervacijaDvorane(int id) {
            return base.Channel.DeleteRezervacijaDvorane(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRezervacijaDvoraneAsync(int id) {
            return base.Channel.DeleteRezervacijaDvoraneAsync(id);
        }
        
        public bool DeleteRezervacijaParkirisca(int id) {
            return base.Channel.DeleteRezervacijaParkirisca(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRezervacijaParkiriscaAsync(int id) {
            return base.Channel.DeleteRezervacijaParkiriscaAsync(id);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[] ListRacun(int idStranka) {
            return base.Channel.ListRacun(idStranka);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[]> ListRacunAsync(int idStranka) {
            return base.Channel.ListRacunAsync(idStranka);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[] ListRacunNeplacani(int idStranka) {
            return base.Channel.ListRacunNeplacani(idStranka);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun[]> ListRacunNeplacaniAsync(int idStranka) {
            return base.Channel.ListRacunNeplacaniAsync(idStranka);
        }
        
        public bool PlacajRacun(int id) {
            return base.Channel.PlacajRacun(id);
        }
        
        public System.Threading.Tasks.Task<bool> PlacajRacunAsync(int id) {
            return base.Channel.PlacajRacunAsync(id);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Soba[] ListMozneRezervacijeSobe(int idHotel, System.DateTime datumOd, System.DateTime datumDo, TehHotel.Gui.Test.RezervacijaServiceSecure.FilterOptionsSoba fos) {
            return base.Channel.ListMozneRezervacijeSobe(idHotel, datumOd, datumDo, fos);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Soba[]> ListMozneRezervacijeSobeAsync(int idHotel, System.DateTime datumOd, System.DateTime datumDo, TehHotel.Gui.Test.RezervacijaServiceSecure.FilterOptionsSoba fos) {
            return base.Channel.ListMozneRezervacijeSobeAsync(idHotel, datumOd, datumDo, fos);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana[] ListMozneRezervacijeDvorane(int idHotel, System.DateTime datumOd, System.DateTime datumDo) {
            return base.Channel.ListMozneRezervacijeDvorane(idHotel, datumOd, datumDo);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana[]> ListMozneRezervacijeDvoraneAsync(int idHotel, System.DateTime datumOd, System.DateTime datumDo) {
            return base.Channel.ListMozneRezervacijeDvoraneAsync(idHotel, datumOd, datumDo);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce[] ListMozneRezervacijeParkirisca(int idHotel, System.DateTime datumOd, System.DateTime datumDo) {
            return base.Channel.ListMozneRezervacijeParkirisca(idHotel, datumOd, datumDo);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce[]> ListMozneRezervacijeParkiriscaAsync(int idHotel, System.DateTime datumOd, System.DateTime datumDo) {
            return base.Channel.ListMozneRezervacijeParkiriscaAsync(idHotel, datumOd, datumDo);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Racun ReadRacun(int Racunid) {
            return base.Channel.ReadRacun(Racunid);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun> ReadRacunAsync(int Racunid) {
            return base.Channel.ReadRacunAsync(Racunid);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Racun ReadRacunStranka(int StrankaId) {
            return base.Channel.ReadRacunStranka(StrankaId);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Racun> ReadRacunStrankaAsync(int StrankaId) {
            return base.Channel.ReadRacunStrankaAsync(StrankaId);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Soba ReadSoba(int SobaId) {
            return base.Channel.ReadSoba(SobaId);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Soba> ReadSobaAsync(int SobaId) {
            return base.Channel.ReadSobaAsync(SobaId);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana ReadDvorana(int DvoranaId) {
            return base.Channel.ReadDvorana(DvoranaId);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Dvorana> ReadDvoranaAsync(int DvoranaId) {
            return base.Channel.ReadDvoranaAsync(DvoranaId);
        }
        
        public TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce ReadParkirisce(int ParkirisceId) {
            return base.Channel.ReadParkirisce(ParkirisceId);
        }
        
        public System.Threading.Tasks.Task<TehHotel.Gui.Test.RezervacijaServiceSecure.Parkirisce> ReadParkirisceAsync(int ParkirisceId) {
            return base.Channel.ReadParkirisceAsync(ParkirisceId);
        }
    }
}
